import { fillerStories } from "@/lib/topstar/fillerStories";
import type {
  AssetManifest,
  ChapterDef,
  EndingDef,
  RecurringEventDef,
  RoutineEventDef,
  ShopItemDef,
  StoryEventDef,
  TopstarGameData,
  TopstarMapDef,
  TurnIndexEntry,
} from "@/lib/topstar/types";

const START_YEAR = 2018;
const START_MONTH = 9;

function getTurnDateLabel(turn: number): string {
  const monthOffset = turn - 1;
  const totalMonth = START_MONTH - 1 + monthOffset;
  const year = START_YEAR + Math.floor(totalMonth / 12);
  const month = (totalMonth % 12) + 1;
  return `${year}年${month}月`;
}

export function getStaminaMaxForTurn(turn: number): number {
  if (turn <= 36) return 10;
  if (turn <= 84) return 15;
  return 20;
}

export const chapters: ChapterDef[] = [
  {
    id: "chapter1",
    title: "初心萌芽篇",
    turnRange: [1, 36],
    timeline: "2018.9 - 2021.8",
    summary: "从深大入学到毕业抉择，陪 EVE 迈出说唱生涯的第一步。",
  },
  {
    id: "chapter2",
    title: "职业启程篇",
    turnRange: [37, 84],
    timeline: "2021.9 - 2025.8",
    summary: "从《黑怕女孩》舞台到职业音乐人，建立稳定作品与舞台影响力。",
  },
  {
    id: "chapter3",
    title: "破圈跃迁篇",
    turnRange: [85, 120],
    timeline: "2025.9 - 2028.8",
    summary: "从音乐节、生日专场与新歌发布继续扩圈，稳稳走向更成熟的职业阶段。",
  },
  {
    id: "chapter4",
    title: "顶流加冕篇",
    turnRange: [121, 144],
    timeline: "2028.9 - 2030.8",
    summary: "完成《宇宙里的星轨》与鸟巢终章，把十年同行写进最终舞台。",
  },
];

export const chapterMaps: TopstarMapDef[] = [
  {
    id: "map_ch1_campus",
    chapterId: "chapter1",
    title: "深大校园",
    summary: "初心萌芽期的校园：从宿舍、琴房到社团活动室，一步步把EVE推向人群。",
    defaultLocationId: "loc_ch1_dorm",
    locations: [
      {
        id: "loc_ch1_practice_room",
        chapterId: "chapter1",
        name: "练习室 / 琴房角",
        shortLabel: "练习室",
        description: "适合日常练声、基础舞台训练和排练加钟。",
        position: { x: 72, y: 34 },
      },
      {
        id: "loc_ch1_dorm",
        chapterId: "chapter1",
        name: "宿舍",
        shortLabel: "宿舍",
        description: "夜里回消息、和家人通电话，也把状态慢慢接回生活。",
        position: { x: 30, y: 32 },
      },
      {
        id: "loc_ch1_club_room",
        chapterId: "chapter1",
        name: "说唱社团活动室",
        shortLabel: "社团",
        description: "F.I.G 队训、队友合作和早期 demo 打磨的起点。",
        position: { x: 52, y: 52 },
      },
      {
        id: "loc_ch1_library",
        chapterId: "chapter1",
        name: "图书馆 / 教学楼",
        shortLabel: "图书馆",
        description: "查资料、拆作品、把行业信息整理成能用的灵感。",
        position: { x: 24, y: 64 },
      },
      {
        id: "loc_ch1_campus_gate",
        chapterId: "chapter1",
        name: "校园路演点",
        shortLabel: "路演点",
        description: "操场边、校门口和临时小舞台，适合小型 live、校园暖场与收工补给。",
        position: { x: 72, y: 72 },
      },
    ],
  },
  {
    id: "map_ch2_city",
    chapterId: "chapter2",
    title: "职业启程城市图",
    summary: "从节目组到录音棚，EVE 的日程第一次被真正排进职业世界。",
    defaultLocationId: "loc_ch2_hotel_room",
    locations: [
      {
        id: "loc_ch2_variety_stage",
        chapterId: "chapter2",
        name: "节目组录制棚",
        shortLabel: "录制棚",
        description: "综艺飞行、常驻录制和舞台复盘发生在这里。",
        position: { x: 73, y: 20 },
      },
      {
        id: "loc_ch2_recording_studio",
        chapterId: "chapter2",
        name: "北京 / 上海录音棚",
        shortLabel: "录音棚",
        description: "录音、后期、商用配唱与热单发布前的最后确认。",
        position: { x: 25, y: 50 },
      },
      {
        id: "loc_ch2_rehearsal_room",
        chapterId: "chapter2",
        name: "职业排练室",
        shortLabel: "排练室",
        description: "练声、走位、排练加钟和舞台肌肉记忆。",
        position: { x: 73, y: 50 },
      },
      {
        id: "loc_ch2_hotel_room",
        chapterId: "chapter2",
        name: "酒店房间",
        shortLabel: "酒店",
        description: "赶通告间隙的休整、家人电话和粉丝社群维护。",
        position: { x: 25, y: 80 },
      },
      {
        id: "loc_ch2_media_room",
        chapterId: "chapter2",
        name: "媒体 / 品牌会议室",
        shortLabel: "媒体间",
        description: "采访提纲、品牌边界和主流乐评都在这里谈妥。",
        position: { x: 73, y: 80 },
      },
      {
        id: "loc_ch2_office",
        chapterId: "chapter2",
        name: "企划办公室",
        shortLabel: "办公室",
        description: "团队例会、公益项目和行业资料复盘的职业中枢。",
        position: { x: 25, y: 20 },
      },
    ],
  },
  {
    id: "map_ch3_breakout",
    chapterId: "chapter3",
    title: "音乐节与新歌地图",
    summary: "城市现场、平台活动、新歌宣发与晚会彩排，把破圈期的路线摊开。",
    defaultLocationId: "loc_ch3_home_corner",
    locations: [
      {
        id: "loc_ch3_album_studio",
        chapterId: "chapter3",
        name: "新歌制作工作室",
        shortLabel: "新歌室",
        description: "单曲、合作曲与下一张概念作品的核心房间。",
        position: { x: 73, y: 20 },
      },
      {
        id: "loc_ch3_company_office",
        chapterId: "chapter3",
        name: "团队企划办公室",
        shortLabel: "办公室",
        description: "例会、行业研究和发行策略从这里统筹。",
        position: { x: 25, y: 50 },
      },
      {
        id: "loc_ch3_media_center",
        chapterId: "chapter3",
        name: "媒体中心 / 品牌摄影棚",
        shortLabel: "媒体中心",
        description: "采访、品牌、社群推广与乐评传播集中在这里。",
        position: { x: 73, y: 50 },
      },
      {
        id: "loc_ch3_gala_rehearsal",
        chapterId: "chapter3",
        name: "大型晚会彩排厅",
        shortLabel: "彩排厅",
        description: "春晚与顶级舞台的前置筹备地点。",
        position: { x: 73, y: 80 },
      },
      {
        id: "loc_ch3_tour_venue",
        chapterId: "chapter3",
        name: "Livehouse / 音乐节场地",
        shortLabel: "现场",
        description: "个人专场、巡演嘉宾、品牌商演和音乐节舞台的执行现场。",
        position: { x: 25, y: 80 },
      },
      {
        id: "loc_ch3_home_corner",
        chapterId: "chapter3",
        name: "家人视频角 / 酒店休息处",
        shortLabel: "休息处",
        description: "给家人回电话、回粉丝消息，也给自己缓一口气。",
        position: { x: 25, y: 20 },
      },
    ],
  },
  {
    id: "map_ch4_crowning",
    chapterId: "chapter4",
    title: "鸟巢终章地图",
    summary: "《宇宙里的星轨》、总控企划与鸟巢主舞台一起进入最后冲刺。",
    defaultLocationId: "loc_ch4_rest_lounge",
    locations: [
      {
        id: "loc_ch4_birdnest_stage",
        chapterId: "chapter4",
        name: "鸟巢主舞台",
        shortLabel: "鸟巢",
        description: "顶级舞台与万人场执行的最后现场。",
        position: { x: 25, y: 20 },
      },
      {
        id: "loc_ch4_rehearsal_hall",
        chapterId: "chapter4",
        name: "总排练厅",
        shortLabel: "排练厅",
        description: "练声、加钟、舞台精修都在这里反复确认。",
        position: { x: 25, y: 50 },
      },
      {
        id: "loc_ch4_album_room",
        chapterId: "chapter4",
        name: "《宇宙里的星轨》创作室",
        shortLabel: "创作室",
        description: "把曾经用来逃离的隧道，写成与重要的人们并肩穿过银河系的星轨。",
        position: { x: 73, y: 20 },
      },
      {
        id: "loc_ch4_press_room",
        chapterId: "chapter4",
        name: "发布会 / 采访间",
        shortLabel: "采访间",
        description: "媒体采访、乐评、版权授权与高规格商务在这里完成最后确认。",
        position: { x: 73, y: 50 },
      },
      {
        id: "loc_ch4_team_office",
        chapterId: "chapter4",
        name: "总控企划室",
        shortLabel: "总控室",
        description: "团队例会、公益运营与行业研究的终章中控台。",
        position: { x: 25, y: 80 },
      },
      {
        id: "loc_ch4_rest_lounge",
        chapterId: "chapter4",
        name: "后台休息室",
        shortLabel: "休息室",
        description: "家人电话、粉丝社群和夜宵补给都在后台慢慢落地。",
        position: { x: 73, y: 80 },
      },
    ],
  },
];

export const routineEvents: RoutineEventDef[] = [
  {
    id: "routine_vocal_practice",
    title: "安排 EVE 日常练声 / 民乐打磨",
    locationId: "loc_ch1_practice_room",
    tier: "light",
    staminaCost: 3,
    description: "把气息、咬字和民乐段落一遍遍练稳，为下一次登台做好准备。",
    outcomeNarratives: [
      "琴房里回声很轻，EVE 一边哼着即兴旋律，一边回头冲你笑：「再来一遍？这次我想把气口留给你和声。」你们从基础音阶练到一段民乐与说唱的拼贴，嗓子微哑，但眼睛很亮。她说有【自定义昵称】在旁边盯进度，她反而不敢偷懒。",
      "她把竹笛横在唇边试了两个长音，又放下揉揉腮帮：「民乐那段我总是太紧。」你帮她录了一小段干声回放，她听着听着就笑了：「原来问题出在换气——你刚才那一声咳嗽都算进拍子里了。」窗外天色渐暗，练习本上记满了歪歪扭扭的备注。",
      "热身时她随口把一段广告旋律改成了说唱腔，你拍手起哄，她反倒不好意思：「别夸，等会儿正课翻车就尴尬了。」结果正课没翻车，只是结束时两个人都嗓子发干，并排坐在台阶上喝同一牌子的矿泉水，像打完一场很小的胜仗。",
    ],
    unlockTurn: 1,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "creativity", delta: 1 },
      { type: "stat", key: "stage", delta: 1 },
    ],
  },
  {
    id: "routine_fan_reply",
    title: "陪 EVE 运营粉丝社群 / 回复留言",
    locationId: "loc_ch1_dorm",
    tier: "light",
    staminaCost: 3,
    description: "认真回应每一份喜欢，让她和小喇叭之间的距离再近一点。",
    outcomeNarratives: [
      "夜里后台消息跳个不停，EVE 捧着手机一条条看过去，偶尔把手机递给你：「这句怎么回才不算敷衍？」你们一起挑了几个走心的回复发出去，又悄悄把一条恶评折叠。她说有人记得她的歌名就够了；你补了一句：有人记得她这个人，也很重要。",
      "有人画了二创头像，她放大看了很久，小声说想私信道谢又怕打扰。你帮她写好一句简短私信，她删删改改，最后只发出去一个「谢谢你喜欢」加一颗爱心——发完又捂脸：「会不会太土？」你摇头：土一点才像真的她。",
      "群里在讨论下一首歌想听什么风格，EVE 犹豫要不要表态。你说：可以只回「在写了」三个字，留一点神秘。她照做，屏幕立刻刷出一排「等你」。她愣了两秒，把手机扣在桌上：「……压力来了，但是好的那种。」",
    ],
    unlockTurn: 1,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "popularity", delta: 1 },
      { type: "stat", key: "bond", delta: 1 },
      { type: "stat", key: "tacit", delta: 1 },
      { type: "counter", key: "fanInteractions", delta: 1 },
    ],
  },
  {
    id: "routine_family_time",
    title: "陪 EVE 和家人通电话 / 回家陪伴",
    locationId: "loc_ch1_dorm",
    tier: "light",
    staminaCost: 3,
    description: "在熟悉的声音里喘口气，把奔波的心重新安顿下来。",
    outcomeNarratives: [
      "电话那头是熟悉的唠叨与关心，EVE 嗯嗯啊啊地应着，指尖无意识地在桌角敲节拍。挂断后她沉默了一会儿，才轻声说：「他们其实不太懂说唱，但懂我累不累。」你递过去一杯温水——外面再吵，这里至少可以先把呼吸放慢。",
      "回家吃饭那天，桌上多摆了一副碗筷给你。她妈妈一边夹菜一边问巡演累不累，EVE 嘴上说着还好，脚下却在桌底轻轻碰了碰你的鞋尖——像在说「帮我说两句真话」。你笑着把话题接过去，饭后她偷偷松了口气。",
      "视频里父亲只问了一句「钱够不够」，EVE 差点鼻酸，嘴上却贫：「够啊，不够再找【自定义昵称】借。」挂了视频她瞪你：「不许笑我。」你说没笑，只是觉得她敢开玩笑了，是好事。",
    ],
    unlockTurn: 1,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "bond", delta: 1 },
    ],
  },
  {
    id: "routine_songwriting",
    title: "陪 EVE 完成 verse 创作 / 编曲 demo 打磨",
    locationId: "loc_ch1_club_room",
    tier: "medium",
    staminaCost: 4,
    description: "从一句灵感开始，把旋律和 verse 慢慢磨成完整的作品。",
    outcomeNarratives: [
      "工程文件里轨道叠了一层又一层，EVE 盯着波形皱眉，把同一句词删了又写。你帮她把灵感碎片钉在白板上，像拼图一样排顺序。凌晨两点，终于有一版 demo 让她愿意按下保存——她伸了个懒腰：「这首要是成了，第一句感谢写给你。」",
      "她卡在一个韵脚上，把笔一扔：「不写了，吃泡面。」你把她拽回来，只许休息十分钟。十分钟后她居然真把那句顺出来了，还顺手多押了一个双关。她得意地晃脑袋：「看吧，泡面是灵感之母。」",
      "你扮演「挑剔听众」，故意挑刺副歌情绪不够。她翻了个白眼，还是把耳机戴回去重录，录到第三遍时声音有点哑，却明显更走心。保存时她嘀咕：「下次别演这么欠揍啊……但有用。」",
    ],
    unlockTurn: 1,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "creativity", delta: 3 },
      { type: "counter", key: "songwritingSessions", delta: 1 },
    ],
  },
  {
    id: "routine_live_show",
    title: "安排 EVE 校园开放麦 / 社团拼盘演出",
    locationId: "loc_ch1_campus_gate",
    tier: "medium",
    staminaCost: 5,
    description: "把《慢慢》和新写的 verse 带到校园小舞台，在熟人之外练习面对真实观众。",
    outcomeNarratives: [
      "教学楼前临时搭起一块不高的舞台，音箱偶尔还会冒出一点电流声。EVE 抱着麦克风唱完《慢慢》，围观的同学从三两个人变成了一小圈。下台后她先问你：「刚才第二段，我是不是没躲开他们的眼睛？」你点头——这一次，她真的把歌唱给了陌生人。",
      "校园开放日的暖场只有十五分钟，你们把两首歌和一段自我介绍反复掐表。上台前她还在小声背词，鼓点一响却稳稳接住了第一句。散场后学生会递来下一次社团拼盘的邀请，她把纸条折好收进口袋：「那就再练一场。」",
      "社团活动室挤满了抱着乐器的人，轮到 EVE 时，台下没有灯牌，只有很近的呼吸和掌声。唱到新写的 verse，她在最后一句临时换了停顿，竟让整间屋子安静了一秒。你在场边记下这一笔：小舞台也会诚实地告诉人，哪里已经能被听见。",
    ],
    unlockTurn: 14,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "stage", delta: 3 },
      { type: "stat", key: "popularity", delta: 2 },
    ],
  },
  {
    id: "routine_release_single",
    title: "企划并发布 EVE 完整原创单曲",
    locationId: "loc_ch2_recording_studio",
    tier: "heavy",
    staminaCost: 9,
    description: "从录制到宣发完整推进，让精心打磨的作品真正抵达听众。",
    outcomeNarratives: [
      "封面定稿、版权确认、发布时间卡在整点——你们像打了一场看不见的仗。发布键按下去的那一刻，EVE 盯着屏幕刷新，指尖有点抖。数字往上跳的时候，她忽然抓住你的手腕：「【自定义昵称】，我们真的把它推到世界面前了。」你说：是世界先听见，你们只是没松手。",
      "上线前一小时她还在改简介里一个标点，被你强行保存：「再改就赶不上吉时了。」她瞪你，却还是点了发布。刷新第一次有人留言「好听」，她把脸埋进臂弯里闷闷地说：「……没白熬。」你拍她后背：本来就没白熬。",
      "宣传物料在社交平台铺开，她一条条转发，配文写得克制又雀跃。夜里她忽然问你：「要是反响一般怎么办？」你说那就再写下一首。她沉默片刻，点头：「行，那约好了，下一首你还得在。」",
    ],
    unlockTurn: 13,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "creativity", delta: 5 },
      { type: "stat", key: "popularity", delta: 8 },
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_industry_research",
    title: "整理行业资讯 / 优秀作品给 EVE 参考",
    locationId: "loc_ch1_library",
    tier: "light",
    staminaCost: 3,
    description: "拆解新作品与行业动向，把听见的东西整理成下一次创作的灵感。",
    outcomeNarratives: [
      "你把本周榜单、采访和制作拆解整理成一页简报。EVE 边看边圈重点，忽然说出一句新想法，像是被某个细节点亮了。",
      "从同类歌手的发行节奏到宣发文案，你们逐条复盘。她把笔记本往你这边推，说这次终于知道下一首该先从哪一段下手。",
      "夜里你们对着几段参考作品反复听，讨论到凌晨。她收耳机时笑了笑：今天不是在追热点，是在把眼光往前挪。",
    ],
    unlockTurn: 1,
    maxPerTurn: 2,
    effects: [{ type: "stat", key: "creativity", delta: 2 }],
  },
  {
    id: "routine_team_retro",
    title: "召开团队企划例会 / 运营复盘",
    locationId: "loc_ch2_office",
    tier: "light",
    staminaCost: 3,
    description: "把行程、作品和传播逐项复盘，让团队下一步走得更清楚。",
    outcomeNarratives: [
      "你把数据墙投在屏幕上，团队逐条过本月执行偏差。EVE 的结论干脆利落：下个月我们按更高标准来。",
      "从宣发转化到演出复盘，大家争论了半小时。最终你和她拍板新策略，会议室里那股犹豫感一下子散了。",
      "例会最后你让每个人说一个可执行改动。EVE 接过白板笔补上关键节点，现场气氛从“讨论”变成了“行动”。",
    ],
    unlockTurn: 37,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_public_welfare_ops",
    title: "推进公益项目日常运营",
    locationId: "loc_ch2_office",
    tier: "light",
    staminaCost: 2,
    description: "把承诺落到持续行动里，让更多人看见舞台之外的认真。",
    outcomeNarratives: [
      "你们和执行方核对了每一笔细节，确保项目真正落地。EVE 说她希望每次署名都对得起“认真”两个字。",
      "探访结束回程的车上，她一直在看现场反馈。你提醒她别太累，她却说：这些真实回应，比热搜数字更有分量。",
      "项目日报发出后，评论区不算喧闹，却很温暖。她把几条留言收藏，说这是值得长期做下去的事。",
    ],
    unlockTurn: 40,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_club_training",
    title: "安排 EVE 参加说唱社团队训 / 队友合作",
    locationId: "loc_ch1_club_room",
    tier: "medium",
    staminaCost: 4,
    description: "在队友的 beat 和反馈里反复磨合，练出属于她的现场节奏。",
    outcomeNarratives: [
      "社团活动室里大家轮流接 verse，EVE 从紧张到放开只用了两轮。她下台时冲你比了个“稳了”的手势。",
      "你们和队友排了一段合作段落，卡拍点卡到嗓子冒烟。最后一次合上时，全场都笑着鼓掌。",
      "复盘时队友给了她很直接的建议，她认真记下。你看见她把那页笔记折角，像是又往前走了一步。",
    ],
    unlockTurn: 1,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "bond", delta: 3 },
      { type: "stat", key: "stage", delta: 2 },
    ],
  },
  {
    id: "routine_studio_recording",
    title: "陪 EVE 进录音棚录歌 / 作品后期",
    locationId: "loc_ch2_recording_studio",
    tier: "medium",
    staminaCost: 4,
    description: "逐句确认演唱与后期，把脑海里的声音还原成更完整的成品。",
    outcomeNarratives: [
      "你盯着工程里每条轨道，EVE 一句一句补录直到情绪贴合。导出试听那刻，她终于松了肩膀。",
      "混音师提出几处问题，你们当场重录修正。她耳机摘下来的第一句话是：这次终于接近我想要的质感。",
      "从主歌到和声你们磨了整晚，最后那条 take 一进来，房间里所有人都点了头。",
    ],
    unlockTurn: 7,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "creativity", delta: 3 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_media_brand",
    title: "对接媒体采访 / 品牌合作事宜",
    locationId: "loc_ch2_media_room",
    tier: "medium",
    staminaCost: 5,
    description: "在镜头和合作邀约前讲清她是谁，也守住作品与表达的边界。",
    outcomeNarratives: [
      "你把采访提纲改到第三版，尽量让表达更像她本人。录制结束后，导演说这段会成为正片重点。",
      "品牌会里你守住了合作边界，也把创作自主权谈了回来。EVE 会后只说一句：这次我们没让步。",
      "从媒体口径到素材审校，你们把每个细节都过了一遍。上线后反馈稳健，风评也更集中在作品本身。",
    ],
    unlockTurn: 37,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "popularity", delta: 3 },
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_variety_guest",
    title: "安排 EVE 综艺飞行嘉宾录制",
    locationId: "loc_ch2_variety_stage",
    tier: "medium",
    staminaCost: 6,
    description: "在新的镜头与观众面前留下记忆点，也积累不同舞台的经验。",
    outcomeNarratives: [
      "录制棚节奏很快，你们把流程卡得很紧。播出预告一放出，评论区已经开始刷她的名字。",
      "她在飞行环节临场加了段即兴，现场反应比预想更热。回后台后她只问你：这次像不像我最好的状态？",
      "你们提前做了风险预案，正式录制几乎零失误。节目组离场前主动发来下一次合作意向。",
    ],
    unlockTurn: 39,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "popularity", delta: 4 },
      { type: "stat", key: "stage", delta: 3 },
      { type: "stat", key: "authority", delta: 1 },
    ],
  },
  {
    id: "routine_tour_single_stop",
    title: "策划执行 EVE 专场演出 / 巡演单站",
    locationId: "loc_ch3_tour_venue",
    tier: "heavy",
    staminaCost: 12,
    description: "从歌单到现场执行亲自盯紧，把一座城市唱成她的新坐标。",
    outcomeNarratives: [
      "从场地走位到返场曲目你们全程盯完，单站执行几乎无瑕疵。散场时应援海还在晃，EVE 久久没说话。",
      "突发状况在开场前十分钟出现，你迅速协调团队兜底。最终这场不仅稳住了，还成了本轮口碑最高的一站。",
      "她在最后一首歌前看向侧台，像在确认你仍在那里。那一秒之后，整场氛围彻底被点燃。",
    ],
    unlockTurn: 48,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 8 },
      { type: "stat", key: "popularity", delta: 12 },
      { type: "stat", key: "bond", delta: 5 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
  {
    id: "routine_variety_resident",
    title: "对接跟进 EVE 综艺常驻全程录制",
    locationId: "loc_ch2_variety_stage",
    tier: "heavy",
    staminaCost: 14,
    description: "在连续录制中稳定输出，让更多观众慢慢认识真实的她。",
    outcomeNarratives: [
      "常驻录制周期很长，你们按周推进内容和状态维护。播出过半时，她的讨论度已经稳定在头部区间。",
      "你替她扛住了流程端的高压，她则在镜头前保持了持续输出。节目口碑与个人声量一并上扬。",
      "录制收官那晚，团队做了整季复盘。最直观的变化是：她被更多人真正听见了。",
    ],
    unlockTurn: 37,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 8 },
      { type: "stat", key: "popularity", delta: 16 },
      { type: "stat", key: "reputation", delta: 3 },
    ],
  },
  {
    id: "routine_album_full_production",
    title: "全流程企划 EVE 新歌 / 概念作品创作",
    locationId: "loc_ch3_album_studio",
    tier: "heavy",
    staminaCost: 15,
    description: "统筹词曲、制作与发行，把零散灵感推进成一套完整作品。",
    outcomeNarratives: [
      "你们把下一首歌的叙事线从零搭起，逐段校准情绪与编排。每一个小节都在回答“这一阶段的她是谁”。",
      "制作周期拉得很长，但你们没用捷径。交母带那天，她说这首歌终于像一个完整的人生切片。",
      "从词到曲到后期团队调度，你们把所有环节串成了闭环。行业内外都开始认真讨论她的新阶段表达。",
    ],
    unlockTurn: 85,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "creativity", delta: 15 },
      { type: "stat", key: "authority", delta: 5 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
  {
    id: "routine_arena_concert",
    title: "策划执行 EVE Livehouse / 音乐节重点场",
    locationId: "loc_ch3_tour_venue",
    tier: "heavy",
    staminaCost: 17,
    description: "用一场扎实的现场接住陌生观众，把舞台热度带回日常。",
    outcomeNarratives: [
      "Livehouse 从联排到开场每一步都不能错，你和团队把风险清单滚动更新到最后一刻。最终全场合唱把所有压力都还成了掌声。",
      "她站在音乐节舞台中央时，观众席的手灯像一片流动的星光。你知道这一站会成为很多人记忆里的名场面。",
      "返场后她在后台抱着你笑，说这不是一个人的胜利。你点头：这是很多城市、很多回合一起堆出来的答案。",
    ],
    unlockTurn: 108,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 14 },
      { type: "stat", key: "popularity", delta: 22 },
      { type: "stat", key: "bond", delta: 10 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
  {
    id: "routine_top_stage_prep",
    title: "筹备鸟巢 / 春晚顶级舞台企划",
    locationId: "loc_ch4_birdnest_stage",
    tier: "heavy",
    staminaCost: 18,
    description: "从节目编排到大型联排逐项确认，为最高规格的舞台做好准备。",
    outcomeNarratives: [
      "顶级舞台筹备没有容错，你们把每个模块都打磨到可上总台标准。她说这次想把十年的路一次唱完。",
      "从视觉总控到演唱编排，所有环节都在并行推进。你们终于把“想象中的舞台”变成了“可以落地的舞台”。",
      "正式联排那天，团队站在空场馆中央看最终走位。没有人说话，但每个人都知道这一步的重量。",
    ],
    unlockTurn: 121,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "creativity", delta: 10 },
      { type: "stat", key: "stage", delta: 10 },
      { type: "stat", key: "popularity", delta: 10 },
      { type: "stat", key: "resilience", delta: 10 },
      { type: "stat", key: "bond", delta: 10 },
      { type: "stat", key: "authority", delta: 10 },
      { type: "stat", key: "reputation", delta: 5 },
      { type: "stat", key: "tacit", delta: 10 },
    ],
  },
  {
    id: "routine_hotel_rest_recovery",
    title: "酒店休整 / 通告间隙补眠",
    locationId: "loc_ch2_hotel_room",
    tier: "light",
    staminaCost: 2,
    description: "趁通告之间补足睡眠，让紧绷的身体和情绪都慢下来。",
    outcomeNarratives: [
      "她把窗帘拉严，闹钟设成只响一次，整个人陷进枕头里像终于关机。你在门外替她把第二天的流程表改轻半档，她醒来第一句话是：「……你偷偷给我留喘息了对吧。」",
      "酒店送餐来得晚，她裹着浴袍扒两口就困得点头。你说先睡，通告我盯着。她含糊地应了一声，十分钟后消息框里跳出一句：「有你真好。」",
      "窗外是陌生城市的霓虹，她在窗边看了一会儿，说想给家里报平安又怕吵醒。你帮她掐好时间拨过去，挂断后她伸了个懒腰：「好了，可以继续当战士了。」",
    ],
    unlockTurn: 37,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "tacit", delta: 1 },
    ],
  },
  {
    id: "routine_hotel_fan_community",
    title: "酒店里运营粉丝社群 / 回复留言",
    locationId: "loc_ch2_hotel_room",
    tier: "light",
    staminaCost: 3,
    description: "在赶路间隙读一读留言，让远处等待的人也收到回应。",
    outcomeNarratives: [
      "客房台灯暖黄，她盘腿坐在床沿一条条翻私信，偶尔把手机递给你：「这句要不要回？」你们挑了几条走心的发出去，又把一条阴阳怪气的直接略过。她说：「在外面跑再忙，也不能让小喇叭觉得被丢下了。」",
      "有人整理了她的舞台截图做成九宫格，她看得入神，半晌才说想转发又怕太频繁。你帮她写好一句感谢，她改了两个标点才发——发完又刷新看有没有回复。",
      "群里在猜她下一首会不会更狠，她犹豫要不要剧透半个字。你说留「在准备」就好，她照做，评论区立刻刷起「等你」。她把手机扣在胸口：「好的压力，我接。」",
    ],
    unlockTurn: 37,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "popularity", delta: 1 },
      { type: "stat", key: "bond", delta: 1 },
      { type: "stat", key: "tacit", delta: 1 },
      { type: "counter", key: "fanInteractions", delta: 1 },
    ],
  },
  {
    id: "routine_home_corner_rest",
    title: "休息处缓口气 / 给自己留白",
    locationId: "loc_ch3_home_corner",
    tier: "light",
    staminaCost: 2,
    description: "暂时关掉工作消息，在密集行程里留一段真正的空白。",
    outcomeNarratives: [
      "她把鞋踢到一边，整个人缩进沙发角，像终于允许自己不是「EVE 企划案里的 EVE」。你递热茶，她捧着杯子说：「就十分钟，什么都不想。」十分钟后她自己先坐直：「好了，可以继续了。」",
      "窗外雨声很细，她对着窗发呆，忽然说：「有时候觉得跑太快，快到自己都追不上。」你没接大道理，只把下一周的硬任务划掉一项。她侧头看你：「……这种默契很犯规。」",
      "她给猫（或者抱枕）录了段语音，语气软得不像台上那个人。发完又删掉，换了一句更克制的给粉丝。你说都可以，她笑：「被你看见软的一面，好像也没那么可怕。」",
    ],
    unlockTurn: 85,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "bond", delta: 1 },
    ],
  },
  {
    id: "routine_home_corner_family_call",
    title: "家人视频角 / 给家里人报平安",
    locationId: "loc_ch3_home_corner",
    tier: "light",
    staminaCost: 3,
    description: "给家里报一声平安，让熟悉的牵挂接住一路奔波。",
    outcomeNarratives: [
      "视频里母亲还是那句「别太累」，父亲则问演出顺不顺。EVE 一一答完，挂断后沉默两秒：「他们不懂舞台，但懂我怕不怕。」你把下一程的硬通告往后挪了半格，她没反对。",
      "她对着镜头比了个耶，说刚结束一场很重要的彩排——其实镜头外你还看见她眼眶有点红。家人只看得见笑，你说这样也好。她点头：「有些软处，留给懂的人就好。」",
      "弟弟在视频里起哄让她唱一句，她真哼了半句又捂嘴。挂断后她说：「家里永远是充电站。」你把这句话记进日程备注：每月至少留一次这种通话。",
    ],
    unlockTurn: 85,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "tacit", delta: 1 },
      { type: "stat", key: "bond", delta: 1 },
    ],
  },
  {
    id: "routine_ch3_office_retro",
    title: "破圈期团队例会 / 发行复盘",
    locationId: "loc_ch3_company_office",
    tier: "light",
    staminaCost: 3,
    description: "复盘作品和现场反馈，把下一阶段的节奏重新排清楚。",
    outcomeNarratives: [
      "白板上同时贴着巡演站点和新歌排期，团队逐条对齐资源。EVE 最后拍板：「现场不能牺牲作品，作品也不能拖现场。」会议室里那种各说各话的感觉一下子散了。",
      "你把上一周的转化数据和现场反馈并排投影，争论集中在「下一首先打口碑还是先打声量」。她听完只说：「两个都要，但顺序我来定。」笔迹落在日历上，像落子。",
      "例会结束她多留十分钟，单独和你过一遍风险清单。她说：「这个阶段最怕的不是忙，是忙乱。」你把清单收成一页，她收进文件夹：「有你在，乱不起来。」",
    ],
    unlockTurn: 85,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_ch3_release_planning",
    title: "统筹新歌发行与宣发节奏",
    locationId: "loc_ch3_company_office",
    tier: "medium",
    staminaCost: 5,
    description: "把作品定位、发布时间与传播内容拧成一股绳，稳稳送到听众面前。",
    outcomeNarratives: [
      "发行表从预热、上线到长尾维护拆成三周，每个节点都标了负责人。她说：「这次不许靠运气，要靠我们提前把坑填平。」你把最后一处冲突改掉，她点头：「可以发预告了。」",
      "平台方提了几个「更爆款」的改法，你们逐条评估后只采纳一半。她会后说：「妥协可以，但不能妥协到不像我。」你把这句话写进对外口径备忘。",
      "宣发物料定稿那晚，她对着封面看了很久，忽然问：「这像不像这一阶段的答案？」你说像。她深吸气：「那就按这个答案，去面对市场。」",
    ],
    unlockTurn: 88,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "creativity", delta: 3 },
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "popularity", delta: 2 },
    ],
  },
  {
    id: "routine_gala_rehearsal_run",
    title: "大型晚会联排 / 走位彩排",
    locationId: "loc_ch3_gala_rehearsal",
    tier: "medium",
    staminaCost: 6,
    description: "在灯光、机位和走位之间反复磨合，让短短几分钟不留遗憾。",
    outcomeNarratives: [
      "彩排厅灯光一打，她站在标记点上像突然进入另一个频道。走位、停步、抬手，每个细节都过到导演点头。你在侧台记时间码，她下来只问一句：「刚才那遍，稳吗？」",
      "耳返里混进一丝杂音，她当场举手叫停，团队迅速排查。重走来一遍时，她比第一遍更松弛——你说这就是专业。她擦汗笑：「怕出错，但更怕装作没事。」",
      "合练结束已经很晚，她还在空场里走最后一遍路线，像把肌肉记忆刻进身体里。你说可以了，她摇头：「顶级舞台，允许彩排很多次，但不允许正式时侥幸一次。」",
    ],
    unlockTurn: 90,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 5 },
      { type: "stat", key: "popularity", delta: 3 },
      { type: "stat", key: "authority", delta: 1 },
    ],
  },
  {
    id: "routine_gala_full_walkthrough",
    title: "春晚级全流程带机彩排",
    locationId: "loc_ch3_gala_rehearsal",
    tier: "heavy",
    staminaCost: 13,
    description: "按正式播出规格完整走台，把每个镜头和音乐节点校准到位。",
    outcomeNarratives: [
      "从候场、升降台到返场，全流程按直播标准跑完一遍。某个衔接点卡了三次，她要求第四次必须过——第四次真的过了，全场安静两秒然后鼓掌。",
      "导播台、灯光、音响三方同时压时间，你在中间协调得像打仗。她下台第一句话却是：「刚才那句词，我想再改半句，情绪更贴。」你说改，但只给十分钟。",
      "带机彩排结束，她看着空舞台很久，说：「这种场子，一辈子可能也就几次。」你把下一阶段的恢复日程递给她：「所以更要留体力给正式那天。」她接过：「听你的。」",
    ],
    unlockTurn: 100,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 10 },
      { type: "stat", key: "popularity", delta: 8 },
      { type: "stat", key: "reputation", delta: 3 },
      { type: "stat", key: "bond", delta: 3 },
    ],
  },
  {
    id: "routine_ch4_rehearsal_light_drill",
    title: "总排练厅基础练声 / 气息巩固",
    locationId: "loc_ch4_rehearsal_hall",
    tier: "light",
    staminaCost: 3,
    description: "用基础练声守住状态，也让最后阶段的表达依旧松弛。",
    outcomeNarratives: [
      "空厅里只有返听和节拍，她从基础音阶练到一段高难度转音，额角沁汗却越练越亮。你说可以收，她摇头：「鸟巢那种场子，气息不能偷懒。」",
      "她把一段新写的 hook 在排练厅里试唱三遍，每遍情绪都不同。你帮她选第二遍，她想了想：「就第二遍，像把心里话唱出来。」",
      "练完她坐在台阶上喝水，忽然说：「以前觉得练声是任务，现在觉得是给自己留底气。」你把这句话记进她的演出备忘。",
    ],
    unlockTurn: 121,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "stage", delta: 2 },
      { type: "stat", key: "creativity", delta: 1 },
    ],
  },
  {
    id: "routine_ch4_rehearsal_vocal",
    title: "总排练厅段落精修 / 舞台加钟",
    locationId: "loc_ch4_rehearsal_hall",
    tier: "medium",
    staminaCost: 5,
    description: "把最难的段落单独拆开，直到气息、动作与情绪严丝合缝。",
    outcomeNarratives: [
      "同一段副歌拆了六遍，从气息到咬字到情绪递进，她要求自己比上一遍更「可直播」。最后一遍结束时，连场务都下意识鼓了掌。",
      "她把走位和演唱绑在一起练，膝盖发酸也不肯停。你说留点给正式场，她抹汗：「现在多流一点，台上就少慌一点。」",
      "排练厅镜子映出两个人影——她在练，你在记问题清单。收工时她说：「这份清单比夸奖有用。」你把清单递还她：「那明天继续按清单扣。」",
    ],
    unlockTurn: 121,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "stage", delta: 4 },
      { type: "stat", key: "resilience", delta: 2 },
    ],
  },
  {
    id: "routine_final_album_demo_polish",
    title: "《宇宙里的星轨》demo 试听与修改",
    locationId: "loc_ch4_album_room",
    tier: "medium",
    staminaCost: 6,
    description: "逐轨试听、逐句修改，让每一位同行者留下的光都能在专辑里找到坐标。",
    outcomeNarratives: [
      "母带试听室里，她闭着眼听到第三轨，忽然举手：「这里情绪断了半拍。」制作人说可以混过去，她坚持重录。重录完，整轨像突然贯通。",
      "你把乐评人可能追问的点标在歌词边，她逐条回应，有的改词，有的决定现场用表达补。她说：「最后一专，不想留‘本可以更好’。」",
      "demo 定稿版本号跳到 v9，她看着文件名笑：「九次才像话。」你说第十次留给正式场，她点头：「那就让第十次留给舞台。」",
    ],
    unlockTurn: 121,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "creativity", delta: 5 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
  {
    id: "routine_final_album_composition",
    title: "《宇宙里的星轨》词曲定稿 / 概念闭环",
    locationId: "loc_ch4_album_room",
    tier: "heavy",
    staminaCost: 16,
    description: "收拢十年间散落的词曲线索，把“逃离的隧道”写成“并肩的星轨”。",
    outcomeNarratives: [
      "概念墙从第一首歌的草稿贴到最后一首的定稿，她用金线把家人、队友、小喇叭与你的位置连成星轨。她退后两步看了很久：「原来我不是一个人跑到这里的。」",
      "词曲争到深夜，某个韵脚改七次，她仍不满意。你说先睡，明天耳朵会告诉你。第二天她醒来第一句话：「第八个韵，对了。」",
      "定稿文件打包发团队时，她手有点抖。你替她把邮件标题改成「终章 · 可以了」，她看着屏幕，很久才点发送：「发吧。发出去就不回头了。」",
    ],
    unlockTurn: 125,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "creativity", delta: 12 },
      { type: "stat", key: "authority", delta: 4 },
      { type: "stat", key: "reputation", delta: 3 },
    ],
  },
  {
    id: "routine_ch4_command_meeting",
    title: "终章总控例会 / 鸟巢冲刺排期",
    locationId: "loc_ch4_team_office",
    tier: "light",
    staminaCost: 3,
    description: "把专辑、舞台和团队排期放到同一张表上，确保所有人朝同一个方向前进。",
    outcomeNarratives: [
      "总控室大屏上同时跑着专辑、媒体、鸟巢三条时间线，任何一条撞车都是事故。你把冲突点标红，她逐条拍板，语气平静得像在拆弹。",
      "团队有人提议砍掉一段非核心环节省体力，她否决：「粉丝看得见细节，我们也看得见。」会议室安静两秒，然后各自领任务。",
      "例会散场她多留你十分钟，只问：「如果我途中想改一个决定，你会拦我吗？」你说会，但只拦一次。她笑：「公平。」",
    ],
    unlockTurn: 121,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "authority", delta: 3 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_ch4_final_charity",
    title: "终章公益项目收官推进",
    locationId: "loc_ch4_team_office",
    tier: "light",
    staminaCost: 2,
    description: "完成长期公益项目的最后一程，让曾经许下的承诺真正落地。",
    outcomeNarratives: [
      "收官报告里每一笔钱、每一次探访都有对应记录，她说：「顶流可以热闹，但这件事必须安静且真实。」你把最后一份签收单放进文件夹，她签字时很慢。",
      "受益方发来一段视频，没有配乐，只有几句感谢。她看了一遍又一遍，说：「这比任何奖项都更像答案。」",
      "团队提议用公益做宣传点，她摇头：「可以告知，不能消费。」你把对外文案改成更克制的版本，她点头：「这样才对。」",
    ],
    unlockTurn: 125,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "reputation", delta: 2 },
      { type: "stat", key: "bond", delta: 2 },
    ],
  },
  {
    id: "routine_backstage_fan_reply",
    title: "后台回复粉丝 / 社群报平安",
    locationId: "loc_ch4_rest_lounge",
    tier: "light",
    staminaCost: 3,
    description: "在登台前回一回等候已久的留言，把彼此的期待带进现场。",
    outcomeNarratives: [
      "化妆镜前的灯还亮着，她趁换场间隙刷几条私信，挑最走心的回复。你说别占太久，她「嗯」一声，手指却多打了一行：「今晚见。」",
      "有人发来鸟巢外场的排队照片，她放大看了很久，说：「他们比我还早到。」你帮她发一条感谢，她补了一句：「别淋雨。」",
      "群里在刷今晚歌单猜测，她犹豫要不要透露半个字。你说留悬念，她发了一个神秘表情，评论区立刻沸腾——她把手机扣在桌上，深吸气：「好了，该上场了。」",
    ],
    unlockTurn: 121,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "popularity", delta: 2 },
      { type: "stat", key: "bond", delta: 1 },
      { type: "stat", key: "tacit", delta: 1 },
      { type: "counter", key: "fanInteractions", delta: 1 },
    ],
  },
  {
    id: "routine_backstage_family_checkin",
    title: "后台给家人报平安 / 短暂休整",
    locationId: "loc_ch4_rest_lounge",
    tier: "light",
    staminaCost: 2,
    description: "忙里偷闲给家人报平安，也提醒彼此别被最后的冲刺压垮。",
    outcomeNarratives: [
      "后台很吵，她躲进休息室角落拨通家里，声音压得很低：「我很好，真的。」挂断后她靠椅背闭了闭眼，你说：「他们信你，因为你在乎。」",
      "父亲只问了一句「脚疼不疼」，她愣住——今天彩排确实站了很久。她说不疼，挂掉后却悄悄揉脚踝。你把医药包推过去，她没嘴硬。",
      "她给母亲看后台的一束花，镜头里笑得很乖。挂断后她说：「让他们看见我笑，比让他们看见我慌，更好。」你把下一程的硬任务再削半格。",
    ],
    unlockTurn: 121,
    maxPerTurn: 2,
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "bond", delta: 2 },
    ],
  },
  /**
   * 主动收入事项：每章提供稳定接单与高投入项目两档选择。
   * 属性效率低于专项养成，但能把体力转成企划金，再投入商店与付费企划。
   * 地点天然限制可用章节，每项每回合最多完成一次。
   */
  {
    id: "routine_income_campus_gig",
    title: "承接校园活动暖场 / 校园商演",
    locationId: "loc_ch1_campus_gate",
    tier: "light",
    staminaCost: 3,
    description: "接下一场校园活动的正式演出，把第一笔舞台报酬带回企划账上。",
    outcomeNarratives: [
      "学生会把装着演出费的信封递来时，EVE 先愣了一下，又低头确认了一遍名字。她小声说：「原来真的会有人愿意为我的舞台付钱。」你把收据夹进企划本：第一笔收入，值得好好记住。",
      "商场校园季的舞台不大，台下却围了好几圈人。EVE 唱完两首原创，主办方当场结清费用，还问下次能不能再合作。回程路上她一直晃着付款截图，笑得比演出时还亮。",
      "校庆暖场结束，负责老师把劳务费转进企划账户。她坚持先请全社团喝水，剩下的才交给你记账：「赚得不多，但这是歌自己挣回来的。」",
    ],
    unlockTurn: 4,
    cooldownTurns: 2,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 35 },
      { type: "stat", key: "stage", delta: 1 },
      { type: "stat", key: "popularity", delta: 1 },
    ],
  },
  {
    id: "routine_income_demo_commission",
    title: "承接社团 demo 制作 / 编曲小单",
    locationId: "loc_ch1_club_room",
    tier: "medium",
    staminaCost: 5,
    description: "替同学完成一支能正式交付的 demo，用更多时间换取更完整的制作报酬。",
    outcomeNarratives: [
      "委托人只带来一段手机哼唱，你们从和弦、节拍一路搭到人声小样。文件交付时，对方戴着耳机听了三遍，爽快把制作费转进企划账户。",
      "社团学弟的 verse 总是卡在同一个拍点，EVE 陪他拆到深夜。成品导出后，他在转账备注里写了「谢谢两位制作人」，她盯着那几个字偷偷笑了很久。",
      "这次小单来回修改了四版，赚得并不轻松。你把修改次数写进下一份报价单，EVE 点头：「认真可以，但认真也应该有价格。」",
    ],
    unlockTurn: 22,
    cooldownTurns: 3,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 55 },
      { type: "stat", key: "creativity", delta: 2 },
      { type: "counter", key: "songwritingSessions", delta: 1 },
    ],
  },
  {
    id: "routine_income_commercial_recording",
    title: "承接商用配唱 / 品牌短片录音",
    locationId: "loc_ch2_recording_studio",
    tier: "medium",
    staminaCost: 5,
    description: "用半天完成一支商用音频，在守住表达边界的同时补充企划预算。",
    outcomeNarratives: [
      "品牌短片只需要十几秒人声，EVE 却认真录了六版。客户最终选中最松弛的一条，结算单发来时她挑眉：「原来控制在十几秒里，也是一门功课。」",
      "商用配唱的旋律并不复杂，难的是既要贴合画面，又不能丢掉她自己的声音。你替她谈下署名，录音棚当天结款，这笔钱正好补上下一次制作预算。",
      "录到最后一条，客户突然要求换一种更甜的唱法。EVE 看向你，你把修改范围重新确认清楚。成片顺利交付，她收下报酬，也没有越过事先划好的边界。",
    ],
    unlockTurn: 37,
    cooldownTurns: 2,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 60 },
      { type: "stat", key: "creativity", delta: 1 },
      { type: "stat", key: "authority", delta: 1 },
    ],
  },
  {
    id: "routine_income_variety_booking",
    title: "承接综艺通告 / 品牌物料拍摄",
    locationId: "loc_ch2_variety_stage",
    tier: "heavy",
    staminaCost: 8,
    description: "拿出大半个月档期完成录制与拍摄，用密集曝光换取一笔可观的项目收入。",
    outcomeNarratives: [
      "棚内录制从上午拖到凌晨，EVE 换了三套造型，还补拍两轮口播。收工时商务确认了付款节点，她揉着肩说：「累是真的，下一首歌的预算也是真的。」",
      "节目组临时增加互动环节，你们守住了不合适的提问，也把有效镜头完整录完。通告费到账后，她先把一部分划给团队，剩下的交给你安排新作品。",
      "品牌物料拍摄比预期更考验镜头表现，她对着监视器一条条修正。成片通过、项目结算，你们不仅带回收入，也更懂得怎样在商业镜头前保留她自己。",
    ],
    unlockTurn: 49,
    cooldownTurns: 3,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 100 },
      { type: "stat", key: "stage", delta: 1 },
      { type: "stat", key: "popularity", delta: 2 },
      { type: "stat", key: "authority", delta: 1 },
    ],
  },
  {
    id: "routine_income_brand_performance",
    title: "承接品牌舞台 / 城市商业演出",
    locationId: "loc_ch3_tour_venue",
    tier: "medium",
    staminaCost: 7,
    description: "把成熟的现场方案带进商业舞台，用一场扎实演出换回下一阶段预算。",
    outcomeNarratives: [
      "品牌夜的流程压得很紧，你们把三首歌重新编成十五分钟 set。落幕时掌声比预想中更久，主办方当晚结款，还把下一座城市的邀约一并发了过来。",
      "城市商业演出结束，EVE 没有急着看热搜，先拉着你复盘耳返和观众反应。财务确认到账后，她指着下一首歌的制作表：「这次赚的，先投回作品里。」",
      "台下既有品牌嘉宾，也有专程赶来的小喇叭。她没有把舞台唱成广告，而是用完整的现场接住两边观众。合作方认可效果，尾款顺利进入企划账户。",
    ],
    unlockTurn: 85,
    cooldownTurns: 2,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 90 },
      { type: "stat", key: "stage", delta: 2 },
      { type: "stat", key: "popularity", delta: 1 },
      { type: "stat", key: "authority", delta: 1 },
    ],
  },
  {
    id: "routine_income_ost_commission",
    title: "承接影视 OST / 定制歌曲委托",
    locationId: "loc_ch3_album_studio",
    tier: "heavy",
    staminaCost: 10,
    description: "为明确的故事与交付期限完成一首定制作品，把创作能力转成更高额的制作收入。",
    outcomeNarratives: [
      "剧方给来的故事梗概只有两页，你们却为了主人公的一句独白改了整晚副歌。终版通过审核时，制作款与署名确认一并发来，EVE 说这次像替另一个人唱完了心事。",
      "OST 截止日期逼得很紧，录音棚的灯连续亮了几个夜晚。交付版本最终一次通过，项目款到账后，你立刻把下一张作品的制作预算补齐。",
      "客户起初想要一首安全的情歌，EVE 提交的版本却保留了自己的叙事角度。几轮沟通后，对方选择尊重创作，定制费用和词曲署名都按新方案落定。",
    ],
    unlockTurn: 91,
    cooldownTurns: 3,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 145 },
      { type: "stat", key: "creativity", delta: 3 },
      { type: "stat", key: "authority", delta: 1 },
      { type: "stat", key: "reputation", delta: 1 },
      { type: "counter", key: "songwritingSessions", delta: 2 },
    ],
  },
  {
    id: "routine_income_copyright_business",
    title: "洽谈歌曲版权授权 / 高规格商务合作",
    locationId: "loc_ch4_press_room",
    tier: "heavy",
    staminaCost: 8,
    description: "让成熟作品获得长期授权价值，也为最终舞台补足充裕的企划预算。",
    outcomeNarratives: [
      "会议桌上摊着厚厚的授权合同，你逐条确认使用范围、期限和署名。EVE 在最后一页签下名字，版权款进入账户时，她说：「作品走得比我们更远，也应该被好好对待。」",
      "合作方希望买断热门歌曲，你们没有答应，改谈限定场景授权。几轮拉锯后，对方接受了更尊重创作者的方案，首笔授权费用随合同一起到账。",
      "高规格商务拍摄结束已近深夜，团队还在会议室核对物料和付款节点。确认尾款到账后，EVE 把预算表推给你：「该给最后的舞台，再多留一点底气了。」",
    ],
    unlockTurn: 121,
    cooldownTurns: 2,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 130 },
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "reputation", delta: 1 },
    ],
  },
  {
    id: "routine_income_top_endorsement",
    title: "签约年度代言 / 头部品牌整合合作",
    locationId: "loc_ch4_press_room",
    tier: "heavy",
    staminaCost: 13,
    description: "投入完整档期完成最高规格商务，在严格筛选合作对象后获得大额企划收入。",
    outcomeNarratives: [
      "年度代言从创意会、平面拍摄一路排到发布会，你替她守住音乐人的表达位置。全部物料验收后，首期合作款到账，足以支撑最后舞台的一轮重要升级。",
      "三个品牌同时递来方案，你们最终只留下价值观最合适的一家。签约会结束，EVE 看着预算表说：「少接一点没关系，接下的就要对得起大家的信任。」",
      "整合合作拍了整整两天，最后一条镜头结束时全场鼓掌。商务团队确认结算与后续资源，EVE 靠在椅背上长出一口气：「这次是真的把名气换成底气了。」",
    ],
    unlockTurn: 125,
    cooldownTurns: 4,
    maxPerTurn: 1,
    effects: [
      { type: "coin", delta: 220 },
      { type: "stat", key: "popularity", delta: 3 },
      { type: "stat", key: "authority", delta: 3 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
  /**
   * B 类：仅企划金、不耗体力（轻 / 中 / 重）。
   * 全局限流：每回合至多完成 1 次任意企划金养成（见 game.ts `goldRoutineSlotUsageKey`）。
   */
  {
    id: "routine_gold_snack_run",
    title: "排练后夜宵补给",
    locationId: "loc_ch1_campus_gate",
    tier: "light",
    staminaCost: 0,
    goldCost: 30,
    description: "收工后带她吃点热的，聊天里把状态接回生活里。",
    outcomeNarratives: [
      "店里快打烊，你们分一碗热汤面。她说今天那句词怎么唱都不对味，你只说先吃完再想，她筷子顿了顿，真的慢下来。",
      "她举着烤串吐槽返听太干，又突然认真：「但刚才那段走位我好像开窍了。」你笑：「这就是夜宵企划的 ROI。」",
      "走出店门夜风很凉，她把外套拉链拉到顶，小声说谢谢。你没接话，只把下一周的排练表在她眼前晃了晃。",
    ],
    unlockTurn: 1,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "resilience", delta: 1 },
      { type: "stat", key: "tacit", delta: 1 },
    ],
  },
  {
    id: "routine_gold_rehearsal_hour_pack",
    title: "排练室小时包（轻量加钟）",
    locationId: "loc_ch1_practice_room",
    tier: "light",
    staminaCost: 0,
    goldCost: 40,
    description: "多买一段固定时段，把一段副歌或走位练到肌肉记忆。",
    outcomeNarratives: [
      "多出来的四十分钟只练一个八拍，她蹲在地上数拍子，像跟自己较劲。你说可以了，她抬头：「再来最后一次，我请客。」",
      "管理员来锁门时你们还在叠和声，她小跑着道歉，回头冲你挤眼：「这小时买得真不亏。」",
      "她把手机架在角落录了一遍完整走位，回放时自己先皱鼻子又笑：「丑，但清楚。」",
    ],
    unlockTurn: 4,
    maxPerTurn: 1,
    effects: [{ type: "stat", key: "stage", delta: 1 }],
  },
  {
    id: "routine_gold_rehearsal_extra",
    title: "排练室加钟 · 抠段落与走位",
    locationId: "loc_ch2_rehearsal_room",
    tier: "medium",
    staminaCost: 0,
    goldCost: 58,
    description: "多租一段排练室，把气息、台步和段落衔接抠细。",
    outcomeNarratives: [
      "空场里只剩返听里的节拍，她把同一段副歌拆了七遍，直到膝盖发酸才肯停。你说「够了，已经够稳」，她抹了把汗笑：「那再稳一遍。」",
      "她把水瓶递给你当临时观众，站在台口小声试麦。加钟的钱花得心疼，但她盯着地板反光里自己的影子，像终于对上了焦。",
      "最后一遍收声时，她对着空荡荡的观众席鞠了一躬——像提前谢过还没来的掌声。",
    ],
    unlockTurn: 7,
    maxPerTurn: 1,
    effects: [{ type: "stat", key: "stage", delta: 2 }],
  },
  {
    id: "routine_gold_social_boost",
    title: "社群推广加油包",
    locationId: "loc_ch3_media_center",
    tier: "medium",
    staminaCost: 0,
    goldCost: 68,
    description: "小额投放换真实曝光与互动，适合发歌前后一周。",
    outcomeNarratives: [
      "后台曲线跳了一下，她盯着屏幕不敢眨眼，像怕数字会缩回去。你说「是真的活人」，她才敢把截图发进小群。",
      "有人留言问下一首什么时候发，她回得比你还快，又删掉重写，最后只发了一个「在写啦」加波浪线。",
      "她一边刷新一边吃凉掉的饭，你说先吃饭再看数据，她嘴上嗯着，筷子却停在半空。",
    ],
    unlockTurn: 13,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "popularity", delta: 2 },
      { type: "counter", key: "fanInteractions", delta: 1 },
    ],
  },
  {
    id: "routine_gold_critic_commission",
    title: "主流乐评深度撰稿",
    locationId: "loc_ch4_press_room",
    tier: "heavy",
    staminaCost: 0,
    goldCost: 95,
    description: "外请乐评人长文拆解作品，沉淀行业侧口碑与话语权。",
    outcomeNarratives: [
      "文章发出来那夜她刷新到凌晨，你说别看评论区，她还是一条条滑过去，最后停在某句「她的切口很诚实」上很久。",
      "采访提纲里有个问题很尖，她答完反而轻松：「被认真听一次，比一百个热搜都踏实。」",
      "你把稿费截图发团队群，备注写「买认真」。她回了个表情包：小狗鞠躬。",
    ],
    unlockTurn: 37,
    maxPerTurn: 1,
    effects: [
      { type: "stat", key: "authority", delta: 3 },
      { type: "stat", key: "reputation", delta: 2 },
    ],
  },
];

/** 企划商店：礼物（可重复限购）+ 大装（终身一次）；解锁回合见策划 */
export const shopItems: ShopItemDef[] = [
  {
    id: "shop_gift_milktea",
    name: "奶茶",
    price: 20,
    description: "楼下顺路带一杯，默契 +1。",
    unlockTurn: 1,
    limit: "perTurn",
    effects: [{ type: "stat", key: "tacit", delta: 1 }],
  },
  {
    id: "shop_gift_snack",
    name: "应援小食盒",
    price: 25,
    description: "排练间隙垫一口，韧度 +1。",
    unlockTurn: 1,
    limit: "perTurn",
    effects: [{ type: "stat", key: "resilience", delta: 1 }],
  },
  {
    id: "shop_gift_lyric_notebook",
    name: "歌词手账与彩色便签",
    price: 30,
    description: "把随时冒出的句子收好，创作力 +1。",
    unlockTurn: 1,
    limit: "every3Turns",
    effects: [{ type: "stat", key: "creativity", delta: 1 }],
  },
  {
    id: "shop_gift_flowers",
    name: "小花束",
    price: 35,
    description: "演出或答辩后的一束温柔，联结 +1。",
    unlockTurn: 4,
    limit: "every3Turns",
    effects: [{ type: "stat", key: "bond", delta: 1 }],
  },
  {
    id: "shop_gift_handwarm",
    name: "护嗓糖 / 暖贴套装",
    price: 30,
    description: "秋冬连轴转时贴得住身体，韧度 +1。",
    unlockTurn: 13,
    limit: "perTurn",
    effects: [{ type: "stat", key: "resilience", delta: 1 }],
  },
  {
    id: "shop_gear_sample_library",
    name: "商用采样与分轨授权包",
    price: 125,
    description: "正版采样与分轨授权，创作与行业话语权各 +2（终身一次）。",
    unlockTurn: 19,
    limit: "once",
    effects: [
      { type: "stat", key: "creativity", delta: 2 },
      { type: "stat", key: "authority", delta: 2 },
    ],
  },
  {
    id: "shop_gear_recorder",
    name: "入门录音设备",
    price: 100,
    description: "电容麦与声卡入门套装，创作力永久 +3（终身一次）。",
    unlockTurn: 7,
    limit: "once",
    effects: [{ type: "stat", key: "creativity", delta: 3 }],
  },
  {
    id: "shop_gear_monitor_headphones",
    name: "封闭式监听耳机",
    price: 110,
    description: "更清楚地听见节拍与气口，创作力 +2、舞台力 +1（终身一次）。",
    unlockTurn: 7,
    limit: "once",
    effects: [
      { type: "stat", key: "creativity", delta: 2 },
      { type: "stat", key: "stage", delta: 1 },
    ],
  },
  {
    id: "shop_gear_mic",
    name: "电容麦套装",
    price: 130,
    description: "人声更干净，舞台力永久 +3（终身一次）。",
    unlockTurn: 13,
    limit: "once",
    effects: [{ type: "stat", key: "stage", delta: 3 }],
  },
  {
    id: "shop_gift_memory_album",
    name: "演出照片纪念册",
    price: 45,
    description: "把一路同行的瞬间贴进同一本册子，联结与默契各 +1。",
    unlockTurn: 25,
    limit: "every3Turns",
    effects: [
      { type: "stat", key: "bond", delta: 1 },
      { type: "stat", key: "tacit", delta: 1 },
    ],
  },
  {
    id: "shop_gear_bamboo_flute",
    name: "竹笛",
    price: 150,
    description: "民乐手感入门，创作力与联结各 +2（终身一次）。",
    unlockTurn: 37,
    limit: "once",
    effects: [
      { type: "stat", key: "creativity", delta: 2 },
      { type: "stat", key: "bond", delta: 2 },
    ],
  },
  {
    id: "shop_gear_stage_wardrobe",
    name: "定制造型与舞台服装",
    price: 160,
    description: "建立更鲜明的舞台视觉，人气 +3、话语权 +2（终身一次）。",
    unlockTurn: 37,
    limit: "once",
    effects: [
      { type: "stat", key: "popularity", delta: 3 },
      { type: "stat", key: "authority", delta: 2 },
    ],
  },
  {
    id: "shop_gear_stage_monitor",
    name: "舞台监听与耳返系统",
    price: 145,
    description: "现场返听更稳，舞台力与人气永久 +2 / +3（终身一次）。",
    unlockTurn: 48,
    limit: "once",
    effects: [
      { type: "stat", key: "stage", delta: 2 },
      { type: "stat", key: "popularity", delta: 3 },
    ],
  },
  {
    id: "shop_gear_vocal_care_case",
    name: "便携雾化与护嗓箱",
    price: 80,
    description: "为密集通告准备完整恢复装备，韧度 +2、舞台力 +1（终身一次）。",
    unlockTurn: 49,
    limit: "once",
    effects: [
      { type: "stat", key: "resilience", delta: 2 },
      { type: "stat", key: "stage", delta: 1 },
    ],
  },
  {
    id: "shop_gear_tour_camera",
    name: "巡演影像记录套装",
    price: 185,
    description: "把现场与幕后沉淀成长期内容，人气 +3、口碑 +2、联结 +1（终身一次）。",
    unlockTurn: 85,
    limit: "once",
    effects: [
      { type: "stat", key: "popularity", delta: 3 },
      { type: "stat", key: "reputation", delta: 2 },
      { type: "stat", key: "bond", delta: 1 },
    ],
  },
  {
    id: "shop_gear_home_studio",
    name: "简易家庭工作台",
    price: 200,
    description: "桌面声学处理与监听一对，创作力与默契各 +2（终身一次）。",
    unlockTurn: 40,
    limit: "once",
    effects: [
      { type: "stat", key: "creativity", delta: 2 },
      { type: "stat", key: "tacit", delta: 2 },
    ],
  },
  {
    id: "shop_gear_master_backup",
    name: "母带备份与工程归档阵列",
    price: 225,
    description: "稳稳保管终章的每一轨，创作力 +3、话语权 +2、默契 +1（终身一次）。",
    unlockTurn: 121,
    limit: "once",
    effects: [
      { type: "stat", key: "creativity", delta: 3 },
      { type: "stat", key: "authority", delta: 2 },
      { type: "stat", key: "tacit", delta: 1 },
    ],
  },
];

export const recurringEvents: RecurringEventDef[] = [
  {
    id: "recurring_birthday",
    title: "EVE 生日专属企划",
    /** 生日按公开资料统一为 12 月 20 日；88 由主线「生日限定专场」承载，此处不重复触发标签 */
    turns: [4, 16, 28, 40, 52, 64, 76, 100, 112, 124, 136],
    type: "mandatory",
    description: "每到十二月，给她留出一段真正属于生日的时间。",
  },
  {
    id: "recurring_awards",
    title: "年度音乐颁奖礼企划",
    turns: [7, 19, 31, 43, 55, 67, 79, 91, 103, 115, 127, 139],
    type: "conditional",
    description: "当作品被更多人听见，新的领奖台也会渐渐向她亮起。",
  },
  {
    id: "recurring_new_semester",
    title: "开学季 / 新阶段企划",
    turns: [1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121, 133],
    type: "mandatory",
    description: "日历翻到新的阶段，行程表上也有了新的方向。",
  },
];

export const storyEvents: StoryEventDef[] = [
  {
    id: "story_turn_001_join_club",
    turn: 1,
    chapterId: "chapter1",
    title: "回合 1 · 新生报到与说唱社团",
    summary: "你陪 EVE 在深大报到，并决定她是否迈出加入说唱社团的第一步。",
    backgroundId: "bg_campus",
    codexId: "codex_turn_001",
    dialogue: [
      {
        id: "turn1_line1",
        speaker: "narrator",
        text: "九月的深圳大学热闹得像一场刚开场的青春电影，而 EVE 的目光停在了说唱社团的招新海报上。",
      },
      {
        id: "turn1_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我其实偷偷写了好久的歌……但我有点怕，怕自己去社团会很丢人。",
      },
      {
        id: "turn1_line3",
        speaker: "npc",
        speakerName: "社团学长",
        text: "零基础也欢迎，关键是你愿不愿意把自己的故事唱出来。",
      },
    ],
    choices: [
      {
        id: "choice_turn1_join",
        label: "怕什么，我们现在就报名，周六队训我陪你去。",
        description: "从第一次队训开始，让她真正走进说唱社团的生活。",
        staminaCost: 3,
        effects: [
          { type: "stat", key: "creativity", delta: 2 },
          { type: "stat", key: "bond", delta: 3 },
          { type: "stat", key: "tacit", delta: 2 },
          { type: "flag:set", key: "joinedFigClub" },
          { type: "event:complete", id: "story_turn_001_join_club" },
          { type: "codex:unlock", id: "codex_turn_001" },
        ],
      },
      {
        id: "choice_turn1_wait",
        label: "先观望一下，等适应了大学生活再决定。",
        description: "先把脚步放慢，但社团最初的磨合与机会不会一直等人。",
        staminaCost: 1,
        effects: [
          { type: "flag:set", key: "clubDecisionDeferred" },
          { type: "event:complete", id: "story_turn_001_join_club" },
          { type: "codex:unlock", id: "codex_turn_001" },
        ],
      },
      {
        id: "choice_turn1_reject",
        label: "还是先专注学业吧，说唱先当作爱好。",
        description: "大学生活会更安稳，她与职业说唱的距离也会被悄悄拉远。",
        effects: [
          { type: "stat", key: "resilience", delta: -1 },
          { type: "stat", key: "tacit", delta: -3 },
          { type: "flag:set", key: "clubRouteRejected" },
          { type: "event:lock", id: "story_turn_037_first_stage" },
          { type: "event:complete", id: "story_turn_001_join_club" },
          { type: "codex:unlock", id: "codex_turn_001" },
        ],
      },
    ],
  },
  {
    id: "story_turn_002_first_training",
    turn: 2,
    chapterId: "chapter1",
    title: "回合 2 · F.I.G 第一次队训",
    summary: "社团活动室里的第一次 verse，陪她跨过「敢开口」这一关。",
    backgroundId: "bg_club_room",
    codexId: "codex_turn_002",
    conditions: {
      requiredFlags: ["joinedFigClub"],
    },
    dialogue: [
      {
        id: "turn2_line1",
        speaker: "npc",
        speakerName: "社团社长",
        text: "欢迎大家加入 F.I.G！今天第一次队训，每个人上来把自己准备的 verse 唱一遍，互相认识一下就好。",
      },
      {
        id: "turn2_line2",
        speaker: "narrator",
        text: "一圈人挨个表演完，社长的目光终于落到她身上。她攥着写满歌词的笔记本，手心全是汗。",
      },
      {
        id: "turn2_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "怎么办……我好紧张。",
      },
    ],
    choices: [
      {
        id: "choice_turn2_original",
        label: "别怕，就像你平时在我面前唱的那样，把你想表达的唱出来就好。",
        description: "走心原创，正式通过考核。",
        staminaCost: 4,
        effects: [
          { type: "stat", key: "creativity", delta: 3 },
          { type: "stat", key: "bond", delta: 2 },
          { type: "stat", key: "stage", delta: 1 },
          { type: "stat", key: "tacit", delta: 2 },
          { type: "flag:set", key: "passedFigAudition" },
          { type: "event:complete", id: "story_turn_002_first_training" },
          { type: "codex:unlock", id: "codex_turn_002" },
        ],
      },
      {
        id: "choice_turn2_cover",
        label: "先唱一段你熟的热门翻唱，稳住场面再说。",
        description: "勉强过关，少了点「她自己」。",
        staminaCost: 2,
        effects: [
          { type: "stat", key: "stage", delta: 1 },
          { type: "stat", key: "bond", delta: 1 },
          { type: "flag:set", key: "figAuditionWeak" },
          { type: "event:complete", id: "story_turn_002_first_training" },
          { type: "codex:unlock", id: "codex_turn_002" },
        ],
      },
      {
        id: "choice_turn2_quit",
        label: "这次算了，和大家说你没准备好。",
        description: "她会离开社团，《慢慢》和校园发歌计划也很难再继续。",
        effects: [
          { type: "stat", key: "resilience", delta: -2 },
          { type: "stat", key: "bond", delta: -1 },
          { type: "stat", key: "tacit", delta: -5 },
          { type: "flag:set", key: "quitFigClub" },
          { type: "event:lock", id: "story_turn_007_first_demo" },
          { type: "event:lock", id: "story_turn_013_slowly" },
          { type: "event:complete", id: "story_turn_002_first_training" },
          { type: "codex:unlock", id: "codex_turn_002" },
        ],
      },
    ],
  },
  {
    id: "story_turn_007_first_demo",
    turn: 7,
    chapterId: "chapter1",
    title: "回合 7 · 网名「17」的第一首 demo",
    summary: "凌晨的宿舍与编曲工程，她第一次要把自己的故事推到陌生人面前。",
    backgroundId: "bg_dorm_night",
    codexId: "codex_turn_007",
    conditions: {
      requiredFlags: ["joinedFigClub"],
      forbiddenFlags: ["quitFigClub"],
      minStats: { creativity: 13 },
      requiredCounters: { songwritingSessions: 1 },
    },
    dialogue: [
      {
        id: "turn7_line1",
        speaker: "narrator",
        text: "工程文件名叫「17 第一首 demo 最终版」。这是她藏了很久的网名，也是她第一次有一首完整的原创可以按下发布键。",
      },
      {
        id: "turn7_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "你说……我真的要发吗？要是没人听，会不会很丢人啊？",
      },
      {
        id: "turn7_line3",
        speaker: "npc",
        speakerName: "社团好友（语音）",
        text: "你写这么好，先发出去再说！大不了就当记录生活嘛。",
      },
    ],
    choices: [
      {
        id: "choice_turn7_full_release",
        label: "填好信息全平台正式发布，我帮你一起做宣发。",
        description: "让「17」的声音第一次走出社团，也为下一首作品积累听众。",
        staminaCost: 5,
        effects: [
          { type: "stat", key: "creativity", delta: 3 },
          { type: "stat", key: "popularity", delta: 5 },
          { type: "stat", key: "tacit", delta: 3 },
          { type: "flag:set", key: "unlockedSlowlyArc" },
          { type: "flag:set", key: "firstDemoPublished" },
          { type: "flag:set", key: "unlockedMusicPlatforms" },
          { type: "event:complete", id: "story_turn_007_first_demo" },
          { type: "codex:unlock", id: "codex_turn_007" },
        ],
      },
      {
        id: "choice_turn7_private",
        label: "先私密上传，只分享给社团好友听。",
        description: "先在熟人之间听取反馈，压力小一些，也很难获得更多关注。",
        staminaCost: 2,
        effects: [
          { type: "stat", key: "creativity", delta: 2 },
          { type: "flag:set", key: "unlockedSlowlyArc" },
          { type: "event:complete", id: "story_turn_007_first_demo" },
          { type: "codex:unlock", id: "codex_turn_007" },
        ],
      },
      {
        id: "choice_turn7_abort",
        label: "先关掉工程，再打磨一阵。",
        description: "暂时避开发布压力，但这份退缩也会让《慢慢》失去继续完成的机会。",
        effects: [
          { type: "flag:set", key: "demoAbandoned" },
          { type: "event:lock", id: "story_turn_013_slowly" },
          { type: "event:complete", id: "story_turn_007_first_demo" },
          { type: "codex:unlock", id: "codex_turn_007" },
        ],
      },
    ],
  },
  {
    id: "story_turn_012_birthday_20",
    turn: 12,
    chapterId: "chapter1",
    title: "回合 12 ·《慢慢》创作前夜",
    summary: "暑假的尾巴，她把喜欢一个人时想靠近又怕错过的犹豫，写进《慢慢》的第一版 demo。",
    backgroundId: "bg_dorm_night",
    codexId: "codex_turn_012",
    dialogue: [
      {
        id: "turn12_line1",
        speaker: "narrator",
        text: "暑假的宿舍安静下来，桌上摊着写满涂改痕迹的歌词本。她把手机亮了又按灭，最后在页角写下：想靠近一点，又怕走得太慢，就真的错过了。",
      },
      {
        id: "turn12_line2",
        speaker: "npc",
        speakerName: "社团好友（语音）",
        text: "你别再研究什么完美对策了。想见他、怕打扰他，靠近了又开始紧张——这才是你现在最真的东西，就把这份别扭写进去。",
      },
      {
        id: "turn12_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我不是想催他给答案，只是想把时间多留一点给他，陪他到处走走看看。可越认真，我就越怕把关系搞砸……这种患得患失，也能写成一首歌吗？",
      },
    ],
    choices: [
      {
        id: "choice_turn12_blow",
        label: "陪她把 demo 录完：别急着替喜欢找答案，先把这份小心翼翼唱清楚。",
        description: "陪她守住这份小心翼翼，把没有说出口的心事唱进 demo。",
        effects: [
          { type: "stat", key: "resilience", delta: 5 },
          { type: "stat", key: "bond", delta: 5 },
          { type: "stat", key: "creativity", delta: 3 },
          { type: "stat", key: "tacit", delta: 3 },
          { type: "event:complete", id: "story_turn_012_birthday_20" },
          { type: "codex:unlock", id: "codex_turn_012" },
        ],
      },
    ],
  },
  {
    id: "story_turn_013_slowly",
    turn: 13,
    chapterId: "chapter1",
    title: "回合 13 ·《慢慢》· 给所有慢慢来的人",
    summary: "开学季的社团活动室，钢琴前奏里，你们把这首歌磨到敢发给全世界听。",
    backgroundId: "bg_club_room",
    codexId: "codex_turn_013",
    conditions: {
      forbiddenFlags: ["demoAbandoned", "quitFigClub"],
      requiredFlags: ["unlockedSlowlyArc"],
    },
    dialogue: [
      {
        id: "turn13_line1",
        speaker: "narrator",
        text: "从暑假那晚的第一句词，到此刻工程文件里的副歌，你们改了近一个月。歌词本边角写着：2019.9，给所有慢慢来的人。",
      },
      {
        id: "turn13_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "这首歌是我目前最满意的作品……真的要正式发出来吗？",
      },
      {
        id: "turn13_line3",
        speaker: "npc",
        speakerName: "社团好友",
        text: "信我，发出去会火的——这绝对能成你的出圈曲。",
      },
    ],
    choices: [
      {
        id: "choice_turn13_full",
        label: "泡录音棚做完终混，全平台正式发布《慢慢》，宣发我全程盯。",
        description: "投入更多时间完成终混和宣发，让《慢慢》走向更远的听众。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 5 },
          { type: "stat", key: "popularity", delta: 12 },
          { type: "stat", key: "reputation", delta: 1 },
          { type: "stat", key: "resilience", delta: 3 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "slowlyReleasedOfficial" },
          { type: "event:complete", id: "story_turn_013_slowly" },
          { type: "codex:unlock", id: "codex_turn_013" },
        ],
      },
      {
        id: "choice_turn13_delay",
        label: "先搁置，期末考完再打磨发布。",
        description: "先把作品留在工程里，等考试结束后再决定它该去哪里。",
        staminaCost: 2,
        effects: [
          { type: "flag:set", key: "slowlyDelayedExam" },
          { type: "event:complete", id: "story_turn_013_slowly" },
          { type: "codex:unlock", id: "codex_turn_013" },
        ],
      },
      {
        id: "choice_turn13_club_only",
        label: "只在社团内部演出，不正式上架。",
        description: "现场经验会留下，但这首歌很难被社团之外的人听见。",
        staminaCost: 1,
        effects: [
          { type: "stat", key: "stage", delta: 2 },
          { type: "stat", key: "bond", delta: 2 },
          { type: "flag:set", key: "slowlyClubOnly" },
          { type: "event:complete", id: "story_turn_013_slowly" },
          { type: "codex:unlock", id: "codex_turn_013" },
        ],
      },
    ],
  },
  {
    id: "story_turn_026_shenzhen_live_guest",
    turn: 26,
    chapterId: "chapter1",
    title: "回合 26 · 深圳演出飞行嘉宾",
    summary: "2020 年 10 月，她第一次以飞行嘉宾身份站上知名说唱歌手的深圳演出现场，面对的观众不再只是校园里的熟人。",
    backgroundId: "bg_concert",
    portraitId: "eve_stage_mic",
    codexId: "codex_turn_026",
    conditions: {
      requiredEvents: ["story_turn_013_slowly"],
      forbiddenFlags: ["slowlyClubOnly"],
      minStats: {
        stage: 24,
        popularity: 18,
      },
    },
    dialogue: [
      {
        id: "turn26_line1",
        speaker: "narrator",
        text: "深圳的 livehouse 后台比校园舞台窄得多，也吵得多。墙上贴着主咖海报，节目单角落里写着她的名字：王澳楠 EVE，飞行嘉宾。",
      },
      {
        id: "turn26_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "他们大多数不是来看我的吧？如果台下没反应怎么办……我是不是唱完就赶紧下去比较好？",
      },
      {
        id: "turn26_line3",
        speaker: "npc",
        speakerName: "演出统筹",
        text: "下一位嘉宾准备。时间不长，但别怯，今晚每个人都是被现场检验的。",
      },
    ],
    choices: [
      {
        id: "choice_turn26_live_story",
        label: "陪她把《慢慢》唱给陌生观众：不抢主场，但要被记住。",
        description: "把校园里写出的歌带上职业舞台，让陌生观众第一次记住她。",
        staminaCost: 6,
        effects: [
          { type: "stat", key: "stage", delta: 6 },
          { type: "stat", key: "popularity", delta: 8 },
          { type: "stat", key: "resilience", delta: 5 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "shenzhenLiveGuest2020" },
          { type: "event:complete", id: "story_turn_026_shenzhen_live_guest" },
          { type: "codex:unlock", id: "codex_turn_026" },
        ],
      },
      {
        id: "choice_turn26_live_safe",
        label: "选择更稳的短段落，先把第一次职业现场安全唱完。",
        description: "稳稳完成第一次职业现场，只是留给观众的记忆点会少一些。",
        staminaCost: 4,
        effects: [
          { type: "stat", key: "stage", delta: 5 },
          { type: "stat", key: "resilience", delta: 3 },
          { type: "stat", key: "popularity", delta: 3 },
          { type: "flag:set", key: "shenzhenLiveGuestSafe" },
          { type: "event:complete", id: "story_turn_026_shenzhen_live_guest" },
          { type: "codex:unlock", id: "codex_turn_026" },
        ],
      },
    ],
  },
  {
    id: "story_turn_035_black_hiphop_invite",
    turn: 35,
    chapterId: "chapter1",
    title: "回合 35 · 《黑怕女孩》邀约",
    summary: "毕业季来到人生岔路口，你要替 EVE 做出是否职业出道的关键决定。",
    codexId: "codex_turn_035",
    conditions: {
      minStats: {
        creativity: 40,
        stage: 30,
        popularity: 35,
      },
      forbiddenFlags: ["clubRouteRejected", "slowlyClubOnly"],
    },
    dialogue: [
      {
        id: "turn35_line1",
        speaker: "npc",
        speakerName: "节目组导演",
        text: "你好，请问是王澳楠吗？我们是腾讯视频《黑怕女孩》节目组。我们循环了你的《慢慢》和全部作品，想正式邀请你参加全程录制。",
      },
      {
        id: "turn35_line2",
        speaker: "narrator",
        text: "桌上一边是毕业论文终稿，一边是爸妈帮她投的国企 offer，入职时间定在九月。电话里的声音还在讲录制周期，而她的目光在两份未来之间来回。",
      },
      {
        id: "turn35_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我想去上海……可我也怕让爸妈失望。这一次，我想听你的。",
      },
      {
        id: "turn35_line4",
        speaker: "npc",
        speakerName: "妈妈（微信）",
        text: "囡囡，国企 offer 人家已经发了，可别犯糊涂。妈妈不是反对你唱歌，是怕你走这条路太苦。",
      },
    ],
    choices: [
      {
        id: "choice_turn35_accept",
        label: "去。梦想不是等稳定之后才开始的，我陪你一起去。",
        description: "放下已经确定的生活，和她一起走进真正的职业舞台。",
        effects: [
          { type: "stat", key: "resilience", delta: 5 },
          { type: "stat", key: "popularity", delta: 3 },
          { type: "stat", key: "tacit", delta: 10 },
          { type: "flag:set", key: "careerRouteAccepted" },
          { type: "event:complete", id: "story_turn_035_black_hiphop_invite" },
          { type: "codex:unlock", id: "codex_turn_035" },
        ],
      },
      {
        id: "choice_turn35_delay",
        label: "先和家里再谈谈，三天内给节目组答复。",
        description: "给家人和自己三天时间，也承担机会在等待中变化的可能。",
        staminaCost: 1,
        effects: [
          { type: "flag:set", key: "careerRouteDelayed" },
          { type: "event:complete", id: "story_turn_035_black_hiphop_invite" },
          { type: "codex:unlock", id: "codex_turn_035" },
        ],
      },
      {
        id: "choice_turn35_reject",
        label: "还是选稳定的工作吧，音乐继续当业余爱好。",
        description: "选择稳定工作，把音乐留在下班后的另一种人生里。",
        effects: [
          { type: "stat", key: "resilience", delta: -3 },
          { type: "stat", key: "creativity", delta: -2 },
          { type: "stat", key: "tacit", delta: -15 },
          { type: "flag:set", key: "careerRouteRejected" },
          { type: "event:lock", id: "story_turn_037_first_stage" },
          { type: "event:complete", id: "story_turn_035_black_hiphop_invite" },
          { type: "codex:unlock", id: "codex_turn_035" },
        ],
      },
    ],
  },
  {
    id: "story_turn_036_birthday_22",
    turn: 36,
    chapterId: "chapter1",
    title: "回合 36 · 上海出发夜 · 录制前的电话",
    summary: "外滩夜景与录制手册旁，她把家人的担心、粉丝的期待和自己的选择一起装进行李箱。",
    backgroundId: "bg_hotel",
    codexId: "codex_turn_036",
    conditions: {
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn36_line1",
        speaker: "narrator",
        text: "行李箱还靠在门边，节目组发来的录制手册摊在桌上。窗外是外滩的灯，手机却震个不停——粉丝群里刷着「节目加油，楠楠一定可以」。",
      },
      {
        id: "turn36_line2",
        speaker: "npc",
        speakerName: "妈妈（电话）",
        text: "囡囡，既然你决定去了，妈妈也不拦你。照顾好自己，累了就回家，家里永远是你的退路。",
      },
      {
        id: "turn36_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "谢谢你愿意陪我来上海……陪我闯这一趟。",
      },
    ],
    choices: [
      {
        id: "choice_turn36_wish",
        label: "陪她整理录制手册：这一战，我们一起扛到底。",
        description: "把出发前的慌张和牵挂说开，让她带着更踏实的心走进录制。",
        effects: [
          { type: "stat", key: "resilience", delta: 8 },
          { type: "stat", key: "bond", delta: 5 },
          { type: "stat", key: "stage", delta: 3 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "event:complete", id: "story_turn_036_birthday_22" },
          { type: "codex:unlock", id: "codex_turn_036" },
        ],
      },
    ],
  },
  {
    id: "story_turn_037_first_stage",
    turn: 37,
    chapterId: "chapter2",
    title: "回合 37 · 《黑怕女孩》初舞台",
    summary: "全国舞台第一战，你要决定 EVE 用哪一首歌向所有人自我介绍。",
    backgroundId: "bg_variety_stage",
    portraitId: "eve_stage_mic",
    codexId: "codex_turn_037",
    conditions: {
      requiredFlags: ["careerRouteAccepted"],
      minStats: {
        creativity: 45,
      },
    },
    dialogue: [
      {
        id: "turn37_line1",
        speaker: "narrator",
        text: "录制棚里聚光灯直直打在舞台中央，台下坐着几位制作人。幕布后，你手里捏着两份台本：一份是走心原创《我妈妈让我好好学习》，一份是她练了很久的快嘴炸场曲。",
      },
      {
        id: "turn37_line2",
        speaker: "npc",
        speakerName: "画外音 · 节目组",
        text: "接下来，让我们有请选手王澳楠！",
      },
      {
        id: "turn37_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我好紧张……走心怕现场不够炸；唱快嘴，又怕那不是最想表达的自己。你帮我选。",
      },
    ],
    choices: [
      {
        id: "choice_turn37_story_song",
        label: "唱《我妈妈让我好好学习》——你的故事才是最打动人的。",
        description: "让作品先替她介绍自己，用最真实的故事争取制作人的认可。",
        staminaCost: 6,
        effects: [
          { type: "stat", key: "creativity", delta: 4 },
          { type: "stat", key: "stage", delta: 3 },
          { type: "stat", key: "popularity", delta: 15 },
          { type: "stat", key: "bond", delta: 3 },
          { type: "stat", key: "tacit", delta: 8 },
          { type: "flag:set", key: "firstStageStorySong" },
          { type: "event:complete", id: "story_turn_037_first_stage" },
          { type: "codex:unlock", id: "codex_turn_037" },
        ],
      },
      {
        id: "choice_turn37_fast_song",
        label: "先用快嘴炸场曲稳住现场，把晋级名额拿下来再说。",
        description: "现场更燃，但离「她是谁」稍远一步。",
        staminaCost: 6,
        effects: [
          { type: "stat", key: "stage", delta: 5 },
          { type: "stat", key: "popularity", delta: 10 },
          { type: "stat", key: "creativity", delta: 1 },
          { type: "stat", key: "tacit", delta: -3 },
          { type: "flag:set", key: "firstStageFastSong" },
          { type: "event:complete", id: "story_turn_037_first_stage" },
          { type: "codex:unlock", id: "codex_turn_037" },
        ],
      },
    ],
  },
  {
    id: "story_turn_039_finale",
    turn: 39,
    chapterId: "chapter2",
    title: "回合 39 ·《黑怕女孩》决赛夜 · PlaneA 全国亚军",
    summary: "从初舞台到决赛的一季赛程，在团体与个人之间，为最后一夜定下舞台。",
    backgroundId: "bg_variety_stage",
    portraitId: "eve_stage_mic",
    codexId: "codex_turn_039",
    conditions: {
      requiredEvents: ["story_turn_037_first_stage"],
      requiredFlags: ["careerRouteAccepted"],
      minStats: {
        creativity: 55,
        stage: 45,
        bond: 35,
      },
    },
    dialogue: [
      {
        id: "turn39_line1",
        speaker: "narrator",
        text: "决赛现场座无虚席，背后大屏播放着从初舞台到决赛的片段。主持人手中的卡片即将宣读最终名次——这一夜，要把三个月的路一次性唱完。",
      },
      {
        id: "turn39_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "等我下来……我们一起拿奖。",
      },
      {
        id: "turn39_line3",
        speaker: "npc",
        speakerName: "主持人",
        text: "恭喜 PlaneA 厂牌获得本届《黑怕女孩》全国亚军！",
      },
    ],
    choices: [
      {
        id: "choice_turn39_group",
        label: "企划 PlaneA 全员合作原创决赛舞台，把团魂与初心一次打满。",
        description: "把每个人的锋芒拼成一个完整舞台，让 PlaneA 被更多人记住。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "creativity", delta: 5 },
          { type: "stat", key: "stage", delta: 5 },
          { type: "stat", key: "popularity", delta: 28 },
          { type: "stat", key: "bond", delta: 10 },
          { type: "stat", key: "resilience", delta: 5 },
          { type: "stat", key: "authority", delta: 14 },
          { type: "stat", key: "reputation", delta: 2 },
          { type: "stat", key: "tacit", delta: 10 },
          { type: "flag:set", key: "finalePlaneATeam" },
          { type: "event:complete", id: "story_turn_039_finale" },
          { type: "codex:unlock", id: "codex_turn_039" },
        ],
      },
      {
        id: "choice_turn39_solo",
        label: "企划 EVE 个人 solo 走心舞台，唱给家人和一路支持她的人。",
        description: "把镜头留给她自己的故事，用最完整的表达回应这段旅程。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "creativity", delta: 8 },
          { type: "stat", key: "stage", delta: 8 },
          { type: "stat", key: "popularity", delta: 25 },
          { type: "stat", key: "resilience", delta: 8 },
          { type: "stat", key: "bond", delta: 5 },
          { type: "stat", key: "authority", delta: 8 },
          { type: "stat", key: "reputation", delta: 2 },
          { type: "stat", key: "tacit", delta: 15 },
          { type: "flag:set", key: "finaleSoloStage" },
          { type: "event:complete", id: "story_turn_039_finale" },
          { type: "codex:unlock", id: "codex_turn_039" },
        ],
      },
    ],
  },
  {
    id: "story_turn_042_let_him_go",
    turn: 42,
    chapterId: "chapter2",
    title: "回合 42 · 热单《让他走》",
    summary: "北京录音棚的凌晨三点，节目收官后的第一首正式单曲上线。",
    backgroundId: "bg_recording_studio",
    codexId: "codex_turn_042",
    conditions: {
      requiredEvents: ["story_turn_039_finale"],
      requiredFlags: ["careerRouteAccepted"],
      minStats: { creativity: 60 },
    },
    dialogue: [
      {
        id: "turn42_line1",
        speaker: "narrator",
        text: "混音师推上最后一轨母带。简介里写着：愿所有女孩，都有说走就走的勇气——那句是你帮她改到最熨帖的一版。",
      },
      {
        id: "turn42_line2",
        speaker: "npc",
        speakerName: "制作人",
        text: "这版可以直接发，旋律抓耳，歌词也戳女生——上线就等刷屏吧。",
      },
      {
        id: "turn42_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "你觉得怎么样？这版……可以按下发布了吗？",
      },
    ],
    choices: [
      {
        id: "choice_turn42_release",
        label: "全平台正式发布《让他走》，宣发排期我来盯。",
        description: "趁情绪还没有冷却完成录制，让这首歌带着最真实的重量上线。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 8 },
          { type: "stat", key: "popularity", delta: 20 },
          { type: "stat", key: "authority", delta: 8 },
          { type: "stat", key: "reputation", delta: 2 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "releasedLetHimGo" },
          { type: "event:complete", id: "story_turn_042_let_him_go" },
          { type: "codex:unlock", id: "codex_turn_042" },
        ],
      },
    ],
  },
  {
    id: "story_turn_056_ni_kuai_lai",
    turn: 56,
    chapterId: "chapter2",
    title: "回合 56 ·《你快来》· 等一场真诚相遇",
    summary: "2023 年 4 月 4 日，《你快来》发行。它把等待、期待与不愿敷衍的真心，唱成一次明亮而主动的邀请。",
    backgroundId: "bg_recording_studio",
    codexId: "codex_turn_056",
    conditions: {
      requiredEvents: ["story_turn_042_let_him_go"],
      requiredFlags: ["careerRouteAccepted"],
      minStats: {
        creativity: 62,
        bond: 42,
      },
    },
    dialogue: [
      {
        id: "turn56_line1",
        speaker: "narrator",
        text: "录音棚窗外刚下过雨，新工程里的旋律却很亮。歌名写着《你快来》，不是命令谁赶紧出现，更像把心里的空位认真整理好，等待一场不敷衍的相遇。",
      },
      {
        id: "turn56_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我想写的不是“没有谁就不行”，而是我知道自己想遇见怎样的人，也愿意为真正的靠近留一盏灯。期待可以主动，但不能委屈自己。",
      },
      {
        id: "turn56_line3",
        speaker: "npc",
        speakerName: "制作人",
        text: "那就让它独立站住。宣发不借前作讲故事，也不只贴“甜歌”标签；重点是她怎样诚实地表达期待，又守住自己的边界。",
      },
    ],
    choices: [
      {
        id: "choice_turn56_release",
        label: "正式发布《你快来》：把对真诚相遇的期待讲清楚。",
        description: "让等待不再被写成被动停留，而是一次清醒、明亮又主动的邀请。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 7 },
          { type: "stat", key: "popularity", delta: 10 },
          { type: "stat", key: "bond", delta: 8 },
          { type: "stat", key: "reputation", delta: 4 },
          { type: "stat", key: "tacit", delta: 6 },
          { type: "flag:set", key: "releasedNiKuaiLai" },
          { type: "event:complete", id: "story_turn_056_ni_kuai_lai" },
          { type: "codex:unlock", id: "codex_turn_056" },
        ],
      },
    ],
  },
  {
    id: "story_turn_062_nvwei_yuejirong",
    turn: 62,
    chapterId: "chapter2",
    title: "回合 62 · 专辑《女为悦己容》",
    summary: "2023 年 10 月 17 日，《女为悦己容》发行。竹笛、女性表达与说唱，被正式拧成 EVE 的辨识度。",
    backgroundId: "bg_recording_studio",
    portraitId: "eve_flute",
    codexId: "codex_turn_062",
    conditions: {
      requiredEvents: ["story_turn_056_ni_kuai_lai"],
      requiredFlags: ["careerRouteAccepted"],
      minStats: {
        creativity: 65,
        resilience: 45,
      },
    },
    dialogue: [
      {
        id: "turn62_line1",
        speaker: "narrator",
        text: "母带导出进度条走到 100%。封面、曲序、简介和最后一版歌词都摊在桌上，标题写着：《女为悦己容》。",
      },
      {
        id: "turn62_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我想让大家听到的不是「谁定义我」，而是「我怎么定义我自己」。竹笛那段别收得太温柔，它也可以很有攻击性。",
      },
      {
        id: "turn62_line3",
        speaker: "npc",
        speakerName: "制作人",
        text: "这张作品的气质很清楚了：女性表达、民乐融合、说唱态度。发出去以后，大家会重新认识她。",
      },
    ],
    choices: [
      {
        id: "choice_turn62_release",
        label: "定版发布《女为悦己容》，把“为自己而唱”的概念打清楚。",
        description: "用一张完整专辑讲清她眼中的女性处境，也让作品替她站稳位置。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "creativity", delta: 10 },
          { type: "stat", key: "authority", delta: 8 },
          { type: "stat", key: "reputation", delta: 5 },
          { type: "stat", key: "tacit", delta: 8 },
          { type: "flag:set", key: "releasedNvweiYuejirong" },
          { type: "event:complete", id: "story_turn_062_nvwei_yuejirong" },
          { type: "codex:unlock", id: "codex_turn_062" },
        ],
      },
    ],
  },
  {
    id: "story_turn_069_new_rap_zhukeling",
    turn: 69,
    chapterId: "chapter2",
    title: "回合 69 ·《中国新说唱2024》· 竹笛与《逐客令》",
    summary: "爱奇艺《中国新说唱2024》录制棚里，她把民乐与说唱拧成一支《逐客令》，让「竹笛说唱」被更多人看见。",
    backgroundId: "bg_variety_stage",
    portraitId: "eve_flute",
    codexId: "codex_turn_069",
    conditions: {
      requiredEvents: ["story_turn_042_let_him_go"],
      requiredFlags: ["careerRouteAccepted", "releasedNvweiYuejirong"],
      minStats: {
        creativity: 70,
        stage: 65,
      },
    },
    dialogue: [
      {
        id: "turn69_line1",
        speaker: "narrator",
        text: "《中国新说唱2024》的候场通道里，她一遍遍试竹笛的气口与进拍。走廊屏幕循环播放节目 logo，而你手里攥着最终版《逐客令》的分轨表。",
      },
      {
        id: "turn69_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "这首歌从《黑怕女孩》之后就在脑子里转……我想让所有人知道，竹笛不只是古风背景，它能跟说唱一起炸场。",
      },
      {
        id: "turn69_line3",
        speaker: "npc",
        speakerName: "节目编导",
        text: "王澳楠老师，五分钟后上台。逐客令那段笛子，现场收音拜托你们再盯一遍。",
      },
    ],
    choices: [
      {
        id: "choice_turn69_stage",
        label: "陪她最后一遍对拍：笛声进、人声顶，把《逐客令》一战打满。",
        description: "让竹笛和说唱在同一个舞台正面相遇，把她的个人标签唱得更清楚。",
        staminaCost: 6,
        effects: [
          { type: "stat", key: "stage", delta: 6 },
          { type: "stat", key: "popularity", delta: 12 },
          { type: "stat", key: "authority", delta: 6 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "performedZhukelingNewRap" },
          { type: "event:complete", id: "story_turn_069_new_rap_zhukeling" },
          { type: "codex:unlock", id: "codex_turn_069" },
        ],
      },
    ],
  },
  {
    id: "story_turn_076_single_rank_comedy",
    turn: 76,
    chapterId: "chapter2",
    title: "回合 76 ·《单排喜剧大赛》· 跨界试错",
    summary: "2024 年 12 月，《单排喜剧大赛》播出。她把说唱、乐器和喜剧节奏放到陌生舞台上，结果不完美，但表达没有退场。",
    backgroundId: "bg_variety_stage",
    portraitId: "eve_stage_mic",
    codexId: "codex_turn_076",
    conditions: {
      requiredEvents: ["story_turn_069_new_rap_zhukeling"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn76_line1",
        speaker: "narrator",
        text: "录制棚里不再是熟悉的说唱竞演节拍，而是单人喜剧的灯光、计时器和观众笑声。台本标题写着《牛博文》，旁边是你们反复改过的 punchline。",
      },
      {
        id: "turn76_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我知道这不是我的主场，但说唱本来就可以吐槽生活、拆开关系、把难堪唱成节奏。就算票数不好看，我也想试一次。",
      },
      {
        id: "turn76_line3",
        speaker: "npc",
        speakerName: "节目导演",
        text: "准备上场。记住，喜剧节奏和 rap 不一样，包袱得等观众接住。",
      },
    ],
    choices: [
      {
        id: "choice_turn76_keep_edge",
        label: "保留说唱锋芒：票数可以不完美，但表达要像她本人。",
        description: "保留她的说唱锋芒，用一次不确定的跨界试出新的表达边界。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 5 },
          { type: "stat", key: "resilience", delta: 8 },
          { type: "stat", key: "reputation", delta: 4 },
          { type: "stat", key: "authority", delta: 4 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "singleRankComedyTried" },
          { type: "event:complete", id: "story_turn_076_single_rank_comedy" },
          { type: "codex:unlock", id: "codex_turn_076" },
        ],
      },
      {
        id: "choice_turn76_play_safe",
        label: "把包袱改得更安全，先争取观众即时反馈。",
        description: "舞台更稳，但个人锋芒会被收掉一点。",
        staminaCost: 6,
        effects: [
          { type: "stat", key: "stage", delta: 5 },
          { type: "stat", key: "popularity", delta: 5 },
          { type: "stat", key: "tacit", delta: -2 },
          { type: "flag:set", key: "singleRankComedySafeCut" },
          { type: "event:complete", id: "story_turn_076_single_rank_comedy" },
          { type: "codex:unlock", id: "codex_turn_076" },
        ],
      },
    ],
  },
  {
    id: "story_turn_079_baituo_baituo",
    turn: 79,
    chapterId: "chapter2",
    title: "回合 79 ·《拜托拜托》· 把喜欢唱得坦荡",
    summary: "2025 年 3 月，《拜托拜托》以更饱满的摇滚质感重新抵达听众，把心动、认真与不愿试探的爱唱得直白。",
    backgroundId: "bg_recording_studio",
    portraitId: "eve_career",
    codexId: "codex_turn_079",
    conditions: {
      requiredEvents: ["story_turn_076_single_rank_comedy"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn79_line1",
        speaker: "narrator",
        text: "录音棚屏幕上并排放着两个工程：早年的《拜托拜托（丘比特）》和这次重新编排的新版。吉他、鼓组与人声一层层推上来，原本轻巧的心动被唱出了更坚定的轮廓。",
      },
      {
        id: "turn79_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "以前写它时更像向丘比特许愿。现在我想把它唱成一种态度：真的喜欢，就把心意讲清楚，不拿试探和算计折磨彼此。",
      },
      {
        id: "turn79_line3",
        speaker: "npc",
        speakerName: "制作人",
        text: "新版的摇滚推进更硬，但别把她的甜和笨拙磨掉。直球不是喊得大声，是每一句都敢承担后果。",
      },
    ],
    choices: [
      {
        id: "choice_turn79_baituo_release",
        label: "保留摇滚推进和直球口吻，让《拜托拜托》完整上线。",
        description: "把不愿试探的真心唱得坦荡，也让早年的创作在新的阶段重新长大。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 6 },
          { type: "stat", key: "stage", delta: 4 },
          { type: "stat", key: "popularity", delta: 8 },
          { type: "stat", key: "bond", delta: 3 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "releasedBaituoBaituo" },
          { type: "event:complete", id: "story_turn_079_baituo_baituo" },
          { type: "codex:unlock", id: "codex_turn_079" },
        ],
      },
    ],
  },
  {
    id: "story_turn_081_love_me_like_this",
    turn: 81,
    chapterId: "chapter2",
    title: "回合 81 ·《请和这样的我恋爱吧》· 敏感也热烈",
    summary: "2025 年 5 月 20 日，《请和这样的我恋爱吧》发行。两分多钟里，她不回避敏感、任性与强烈渴望，也不把真实的自己藏进安全答案。",
    backgroundId: "bg_recording_studio",
    portraitId: "eve_career",
    codexId: "codex_turn_081",
    conditions: {
      requiredEvents: ["story_turn_079_baituo_baituo"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn81_line1",
        speaker: "narrator",
        text: "五月二十日的发布排期停在零点。短短两分多钟，副歌几乎没有给情绪留退路：想靠近、会吃醋、害怕失去，也仍然希望对方看见完整的她。",
      },
      {
        id: "turn81_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我不想把敏感写成可爱的装饰，也不想假装自己永远大方。喜欢一个人时，我确实会热烈、会想要很多——但至少这次，我愿意诚实地承认。",
      },
      {
        id: "turn81_line3",
        speaker: "npc",
        speakerName: "发行统筹",
        text: "歌名已经把问题问得很直接。宣发别只贴一个“甜歌”标签，要让大家听见她是在邀请别人认识真实的自己。",
      },
    ],
    choices: [
      {
        id: "choice_turn81_love_me_release",
        label: "不回避矛盾与敏感，按完整自白发布《请和这样的我恋爱吧》。",
        description: "让热烈不只是一句甜蜜口号，也成为一次诚实展示自己的邀请。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 6 },
          { type: "stat", key: "popularity", delta: 10 },
          { type: "stat", key: "bond", delta: 6 },
          { type: "stat", key: "reputation", delta: 3 },
          { type: "stat", key: "tacit", delta: 5 },
          { type: "flag:set", key: "releasedLoveMeLikeThis" },
          { type: "event:complete", id: "story_turn_081_love_me_like_this" },
          { type: "codex:unlock", id: "codex_turn_081" },
        ],
      },
    ],
  },
  {
    id: "story_turn_084_shenzhen_arena",
    turn: 84,
    chapterId: "chapter2",
    title: "回合 84 · 2025 夏季现场地图",
    summary: "重庆专场、日照汽水音乐 Chill 派对、广州与长沙巡演嘉宾，2025 的夏天把 EVE 推向更多城市。",
    backgroundId: "bg_concert",
    portraitId: "eve_career",
    codexId: "codex_turn_084",
    conditions: {
      requiredEvents: ["story_turn_076_single_rank_comedy"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn84_line1",
        speaker: "narrator",
        text: "行程表被你贴满便利贴：3 月《拜托拜托》上线与校园 LIVE，4 月武汉巡演嘉宾，5 月《请和这样的我恋爱吧》发布和重庆专场，6 月日照音乐节，7 月广州与长沙嘉宾场。每个城市都不算终点，却都在把她的现场版图一点点点亮。",
      },
      {
        id: "turn84_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "以前我总觉得自己是在一首歌里等人听见，现在好像真的能走到他们面前唱。就是……城市太多了，我怕状态跟不上。",
      },
      {
        id: "turn84_line3",
        speaker: "npc",
        speakerName: "现场执行",
        text: "重庆站确认重启，日照音乐节和后面几个嘉宾场也在排。你们要决定：这一轮是冲曝光，还是稳现场口碑。",
      },
      {
        id: "turn84_line4",
        speaker: "narrator",
        text: "这是职业启程篇的收束：不靠虚构的一夜体育馆封神，而是靠一场场真实的 livehouse、音乐节和嘉宾舞台，把名字唱进更多城市。",
      },
    ],
    choices: [
      {
        id: "choice_turn84_close",
        label: "做“城市现场地图”：每站复盘歌单、返听和粉丝互动，稳稳扩圈。",
        description: "把每一站的经验带到下一座城市，让现场和听众一起慢慢长大。",
        effects: [
          { type: "stat", key: "stage", delta: 12 },
          { type: "stat", key: "popularity", delta: 22 },
          { type: "stat", key: "bond", delta: 10 },
          { type: "stat", key: "resilience", delta: 8 },
          { type: "stat", key: "authority", delta: 10 },
          { type: "stat", key: "reputation", delta: 6 },
          { type: "stat", key: "tacit", delta: 12 },
          { type: "flag:set", key: "summer2025LiveMap" },
          { type: "event:complete", id: "story_turn_084_shenzhen_arena" },
          { type: "codex:unlock", id: "codex_turn_084" },
        ],
      },
    ],
  },
  {
    id: "story_turn_085_album_direction",
    turn: 85,
    chapterId: "chapter3",
    title: "回合 85 · 厦门数字音乐年度盛典",
    summary: "2025 年 9 月，第三章从厦门第二届数字音乐年度盛典开始：她带着现场经验和作品风格进入更大的平台活动。",
    backgroundId: "bg_concert",
    portraitId: "eve_breakout",
    codexId: "codex_turn_085",
    conditions: {
      requiredEvents: ["story_turn_084_shenzhen_arena"],
    },
    dialogue: [
      {
        id: "turn85_line1",
        speaker: "narrator",
        text: "厦门的海风把后台通道吹得很潮，舞台表贴着“第二届数字音乐年度盛典”。你把前几个月的现场复盘翻到最后一页，写下第三章的目标：让每一次公开活动都留下清楚的 EVE 标签。",
      },
      {
        id: "turn85_line2",
        speaker: "npc",
        speakerName: "活动统筹",
        text: "楠姐，今晚舞台时间不长，但阵容很杂。你们要把记忆点压在最短的 set 里。",
      },
      {
        id: "turn85_line3",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "那就别贪多。让他们记住我的声音、竹笛，还有我为什么唱这些歌。",
      },
    ],
    choices: [
      {
        id: "choice_turn85_fusion",
        label: "压缩成“竹笛说唱 + 女性表达”短 set，记忆点优先。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "creativity", delta: 8 },
          { type: "stat", key: "stage", delta: 6 },
          { type: "stat", key: "popularity", delta: 10 },
          { type: "stat", key: "authority", delta: 5 },
          { type: "stat", key: "tacit", delta: 8 },
          { type: "flag:set", key: "albumRouteFusion" },
          { type: "event:complete", id: "story_turn_085_album_direction" },
          { type: "codex:unlock", id: "codex_turn_085" },
        ],
      },
      {
        id: "choice_turn85_emotion",
        label: "把《让他走》和治愈向作品放进歌单，优先打情绪共鸣。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "bond", delta: 8 },
          { type: "stat", key: "resilience", delta: 5 },
          { type: "stat", key: "popularity", delta: 12 },
          { type: "stat", key: "reputation", delta: 4 },
          { type: "stat", key: "tacit", delta: 10 },
          { type: "flag:set", key: "albumRouteEmotion" },
          { type: "event:complete", id: "story_turn_085_album_direction" },
          { type: "codex:unlock", id: "codex_turn_085" },
        ],
      },
      {
        id: "choice_turn85_experiment",
        label: "加入新编曲和 live 改编，先拓宽现场边界。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 5 },
          { type: "stat", key: "stage", delta: 8 },
          { type: "stat", key: "popularity", delta: 6 },
          { type: "stat", key: "tacit", delta: 3 },
          { type: "flag:set", key: "albumRouteExperiment" },
          { type: "event:complete", id: "story_turn_085_album_direction" },
          { type: "codex:unlock", id: "codex_turn_085" },
        ],
      },
    ],
  },
  {
    id: "story_turn_088_changsha_birthday_live",
    turn: 88,
    chapterId: "chapter3",
    title: "回合 88 · 长沙生日限定专场",
    summary: "2025 年 12 月 27 日，MAO Livehouse 长沙。生日限定专场把旧歌、新歌、粉丝互动和这一年的奔波一起唱成回顾。",
    backgroundId: "bg_concert",
    portraitId: "eve_breakout",
    codexId: "codex_turn_088",
    conditions: {
      requiredEvents: ["story_turn_085_album_direction"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn88_line1",
        speaker: "narrator",
        text: "长沙 MAO Livehouse 的后台贴着生日限定专场流程表：萌芽之时、光芒初现、内心对话、未来可期。你看着这些分段，像看见她从「17」一路走到 EVE 的目录。",
      },
      {
        id: "turn88_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "这不是最大的场地，但我想把它做成最像我们的场地。老歌要唱，新歌也要留一点线索，小喇叭来一趟不能只听热闹。",
      },
      {
        id: "turn88_line3",
        speaker: "npc",
        speakerName: "现场工作人员",
        text: "EVIP 面签、伴手礼、合影、TO 签海报都排进来了。时间很紧，歌单和互动必须卡准。",
      },
    ],
    choices: [
      {
        id: "choice_turn88_memory_setlist",
        label: "做“四段式歌单”：从《慢慢》唱到新歌预告，把一路走来的故事讲完整。",
        description: "用旧歌、新作与现场互动，把她和小喇叭共同走过的时间唱完整。",
        staminaCost: 12,
        effects: [
          { type: "stat", key: "stage", delta: 8 },
          { type: "stat", key: "bond", delta: 14 },
          { type: "stat", key: "popularity", delta: 12 },
          { type: "stat", key: "reputation", delta: 6 },
          { type: "stat", key: "tacit", delta: 16 },
          { type: "counter", key: "fanInteractions", delta: 4 },
          { type: "flag:set", key: "changshaBirthdayLive2025" },
          { type: "event:complete", id: "story_turn_088_changsha_birthday_live" },
          { type: "codex:unlock", id: "codex_turn_088" },
        ],
      },
      {
        id: "choice_turn88_new_song_tease",
        label: "把重心放在新歌预告和改编舞台，让生日场成为下一阶段入口。",
        description: "让新歌与改编舞台成为主角，把生日现场变成下一段旅程的预告。",
        staminaCost: 12,
        effects: [
          { type: "stat", key: "creativity", delta: 8 },
          { type: "stat", key: "stage", delta: 10 },
          { type: "stat", key: "popularity", delta: 16 },
          { type: "stat", key: "authority", delta: 6 },
          { type: "stat", key: "tacit", delta: 8 },
          { type: "flag:set", key: "changshaBirthdayNewSongTease" },
          { type: "event:complete", id: "story_turn_088_changsha_birthday_live" },
          { type: "codex:unlock", id: "codex_turn_088" },
        ],
      },
    ],
  },
  {
    id: "story_turn_090_zaiganma_release",
    turn: 90,
    chapterId: "chapter3",
    title: "回合 90 · 情人节合作曲《在干嘛？》",
    summary: "2026 年 2 月 14 日，与圣代合作的新单曲《在干嘛？》发行。合作曲把她的情绪叙事放进更轻巧的问候里。",
    backgroundId: "bg_recording_studio",
    codexId: "codex_turn_090",
    conditions: {
      requiredEvents: ["story_turn_088_changsha_birthday_live"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn90_line1",
        speaker: "narrator",
        text: "情人节零点前，合作曲的封面、简介和发布排期都已经确认。歌名只有三个字：《在干嘛？》像一条没发出去又舍不得删的消息。",
      },
      {
        id: "turn90_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "这首别做得太重。它像一句很轻的问候，但问出口之前，其实已经在心里绕了很多圈。",
      },
      {
        id: "turn90_line3",
        speaker: "npc",
        speakerName: "合作方统筹",
        text: "圣代老师那边确认同步宣发。你们这边准备好短视频切片和粉丝文案就可以上了。",
      },
    ],
    choices: [
      {
        id: "choice_turn90_soft_release",
        label: "按情人节情绪线发布：轻一点，但每一句都要有回声。",
        description: "借一句轻轻的问候打开合作曲，让两种声音自然走进同一段情绪。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 6 },
          { type: "stat", key: "popularity", delta: 12 },
          { type: "stat", key: "bond", delta: 6 },
          { type: "stat", key: "authority", delta: 4 },
          { type: "stat", key: "tacit", delta: 6 },
          { type: "flag:set", key: "releasedZaiganma" },
          { type: "event:complete", id: "story_turn_090_zaiganma_release" },
          { type: "codex:unlock", id: "codex_turn_090" },
        ],
      },
    ],
  },
  {
    id: "story_turn_091_jiekou_changzhou_qishui",
    turn: 91,
    chapterId: "chapter3",
    title: "回合 91 ·《街口》与常州汽水音乐节",
    summary: "2026 年 3 月，《街口》发行后接上常州汽水音乐节。新歌和春季户外舞台，把 2026 的现场线正式打开。",
    backgroundId: "bg_concert",
    portraitId: "eve_stage_mic",
    codexId: "codex_turn_091",
    conditions: {
      requiredEvents: ["story_turn_090_zaiganma_release"],
      requiredFlags: ["careerRouteAccepted"],
    },
    dialogue: [
      {
        id: "turn91_line1",
        speaker: "narrator",
        text: "《街口》上线一周后，常州新龙生态林的音乐节舞台开始搭建。春天的户外风很大，你一边盯舞台时间，一边确认新歌 live 版的进拍点。",
      },
      {
        id: "turn91_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "《街口》这首歌很像我现在的状态：站在路口，但不慌。前面还有很多方向，我们就一个一个走。",
      },
      {
        id: "turn91_line3",
        speaker: "npc",
        speakerName: "音乐节执行",
        text: "常州汽水音乐节 DAY1，王澳楠 EVE 已确认。户外返听和风噪我们会再测一遍，你们准备好现场版编排。",
      },
    ],
    choices: [
      {
        id: "choice_turn91_jiekou_live",
        label: "把《街口》做成春季现场首唱重点，接住常州音乐节的人群。",
        description: "让新歌在春季户外舞台第一次落地，也接住更大范围的现场听众。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "creativity", delta: 6 },
          { type: "stat", key: "stage", delta: 10 },
          { type: "stat", key: "popularity", delta: 18 },
          { type: "stat", key: "reputation", delta: 5 },
          { type: "stat", key: "tacit", delta: 8 },
          { type: "flag:set", key: "releasedJiekouAndChangzhouQishui" },
          { type: "event:complete", id: "story_turn_091_jiekou_changzhou_qishui" },
          { type: "codex:unlock", id: "codex_turn_091" },
        ],
      },
    ],
  },
  {
    id: "story_turn_114_chunwan",
    turn: 114,
    chapterId: "chapter3",
    title: "回合 114 · 央视春晚邀约",
    summary: "红色邀约函摆在桌上——【春晚曲目】将要在除夕夜唱给全国观众听。",
    backgroundId: "bg_gala",
    codexId: "codex_turn_114",
    conditions: {
      requiredEvents: ["story_turn_091_jiekou_changzhou_qishui"],
      minStats: {
        stage: 100,
        reputation: 70,
        popularity: 100,
        authority: 80,
      },
    },
    dialogue: [
      {
        id: "turn114_line1",
        speaker: "npc",
        speakerName: "经纪人",
        text: "楠姐！是春晚！央视春晚！这是对国民度和专业的最高认可之一，我们接不接？",
      },
      {
        id: "turn114_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "我们……真的能上春晚了？我妈以前总说，哪天我上春晚，她就真的为我骄傲。",
      },
      {
        id: "turn114_line3",
        speaker: "narrator",
        text: "你想起深大宿舍里那个不敢点发布的女孩。从校园 demo、综艺舞台、音乐节现场到除夕直播，这条路终于接到了新的想象。",
      },
    ],
    choices: [
      {
        id: "choice_turn114_accept",
        label: "接。我来全程对接彩排，我们把【春晚曲目】带上除夕夜。",
        description: "把她的作品带到全国观众面前，也接受最高规格舞台的检验。",
        staminaCost: 10,
        effects: [
          { type: "stat", key: "stage", delta: 10 },
          { type: "stat", key: "reputation", delta: 18 },
          { type: "stat", key: "popularity", delta: 35 },
          { type: "stat", key: "authority", delta: 20 },
          { type: "stat", key: "tacit", delta: 15 },
          { type: "flag:set", key: "chunwanAccepted" },
          { type: "event:complete", id: "story_turn_114_chunwan" },
          { type: "codex:unlock", id: "codex_turn_114" },
        ],
      },
      {
        id: "choice_turn114_decline",
        label: "先婉拒，把体力留给海外专场与创作闭关。",
        description: "把时间留给海外舞台和创作闭关，但这次分歧会在你们之间留下波澜。",
        staminaCost: 8,
        effects: [
          { type: "stat", key: "creativity", delta: 8 },
          { type: "stat", key: "stage", delta: 5 },
          { type: "stat", key: "tacit", delta: -10 },
          { type: "flag:set", key: "chunwanDeclined" },
          { type: "event:complete", id: "story_turn_114_chunwan" },
          { type: "codex:unlock", id: "codex_turn_114" },
        ],
      },
    ],
  },
  {
    id: "story_turn_121_ultimate_album",
    turn: 121,
    chapterId: "chapter4",
    title: "回合 121 · 终极专辑《宇宙里的星轨》",
    summary: "从前，创作是宇宙留给她的一条逃离隧道；现在，她要和重要的人们一起，把整段路走成并肩穿过银河系的星轨。",
    backgroundId: "bg_campus",
    codexId: "codex_turn_121",
    conditions: {
      minTurn: 121,
      minStats: {
        creativity: 140,
        authority: 100,
      },
    },
    dialogue: [
      {
        id: "turn121_line1",
        speaker: "narrator",
        text: "窗外香樟树的风声和当年一样。旧歌词本里，写歌曾是她逃离误解、沉默与胆怯的一条窄窄隧道；今天，你在新企划封面上写下专辑名——《宇宙里的星轨》。",
      },
      {
        id: "turn121_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "以前我总觉得，只要一个人沿着隧道跑得够久，就能逃到有光的地方。后来才发现，爸妈、PlaneA、小喇叭，还有你——每个人都在这条路上留下了坐标。",
      },
      {
        id: "turn121_line3",
        speaker: "narrator",
        text: "她在概念页中央写下整张专辑的核心句：我们是彼此宇宙里的星轨，并肩穿过银河系。那条曾用来逃离的路，终于有了共同前往的方向。",
      },
    ],
    choices: [
      {
        id: "choice_turn121_launch",
        label: "拍板启动《宇宙里的星轨》：把十年同行者的光连向鸟巢。",
        description: "调动整个团队完成专辑，让曾经的逃离隧道变成所有重要的人并肩前行的星轨。",
        staminaCost: 20,
        effects: [
          { type: "stat", key: "creativity", delta: 10 },
          { type: "stat", key: "stage", delta: 10 },
          { type: "stat", key: "popularity", delta: 10 },
          { type: "stat", key: "resilience", delta: 10 },
          { type: "stat", key: "bond", delta: 10 },
          { type: "stat", key: "authority", delta: 10 },
          { type: "stat", key: "reputation", delta: 3 },
          { type: "stat", key: "tacit", delta: 20 },
          { type: "flag:set", key: "ultimateAlbumLaunched" },
          { type: "event:complete", id: "story_turn_121_ultimate_album" },
          { type: "codex:unlock", id: "codex_turn_121" },
        ],
      },
    ],
  },
  {
    id: "story_turn_144_finale",
    turn: 144,
    chapterId: "chapter4",
    title: "回合 144 · 鸟巢终章 · 星轨汇流",
    summary: "《慢慢》的第一个音符从十年前出发，最终汇入《宇宙里的星轨》；九万人的灯海，把一路同行的人连成同一片银河。",
    backgroundId: "bg_birdnest",
    portraitId: "eve_topstar",
    codexId: "codex_turn_144",
    dialogue: [
      {
        id: "turn144_line1",
        speaker: "narrator",
        text: "大屏从 2018 年的新生报到一路铺到此刻的鸟巢：深大宿舍、PlaneA 舞台、父母等她回家的灯、小喇叭举起的灯牌，还有始终站在侧台的你。每一道光都从不同方向出发，最终在穹顶汇成星轨。",
      },
      {
        id: "turn144_line2",
        speaker: "eve",
        speakerName: "王澳楠",
        text: "从前，我把音乐当成一条逃离的隧道，以为只要一直跑，就能独自抵达有光的地方。后来我才知道，爸妈、PlaneA 的姐妹们、小喇叭们，还有【自定义昵称】——你们从来不是站在出口等我，而是和我一起，把那段路走成了星轨。我们是彼此宇宙里的星轨，并肩穿过银河系。",
      },
      {
        id: "turn144_line3",
        speaker: "narrator",
        text: "全场顺着她的目光看向侧台，欢呼声像银河翻涌。聚光灯里的她，既是校园 rapper、家人的女儿、PlaneA 的队友，也是小喇叭们一路喜欢的人；而侧台的你，是与她并肩十年的伙伴。所有身份与同行者，在这一晚落进同一条星轨。",
      },
    ],
    choices: [
      {
        id: "choice_turn144_complete",
        label: "和她一起走进汇流的灯海，并肩穿过这片银河。",
        effects: [
          { type: "event:complete", id: "story_turn_144_finale" },
          { type: "codex:unlock", id: "codex_turn_144" },
        ],
      },
    ],
  },
];

export const endings: EndingDef[] = [
  {
    id: "ending_official_topstar",
    category: "official",
    title: "楠得初心 · 全网顶流",
    description: "以《宇宙里的星轨》和鸟巢终章完成顶流加冕，也把十年同行者的光留在最终舞台。",
    conditions: {
      minTurn: 144,
      minStats: {
        creativity: 310,
        stage: 350,
        popularity: 370,
        resilience: 140,
        bond: 250,
        authority: 180,
        reputation: 250,
        tacit: 100,
      },
    },
  },
  {
    id: "ending_branch_office_worker",
    category: "branch",
    title: "斜杠音乐人 · 业余星光",
    description: "回合 35 选择稳定路线，进入平行人生支线。",
    conditions: {
      requiredFlags: ["careerRouteRejected"],
    },
  },
  {
    id: "ending_branch_label_leader",
    category: "branch",
    title: "厂牌主理人 · 行业领航",
    description: "话语权与口碑长期领先，最终从台前艺人成长为行业主理人与标准制定者。",
    conditions: {
      minTurn: 144,
      requiredFlags: ["careerRouteAccepted"],
      minStats: {
        authority: 240,
        reputation: 240,
        popularity: 220,
        bond: 170,
      },
    },
  },
  {
    id: "ending_branch_culture_export",
    category: "branch",
    title: "国风先行者 · 文化出海",
    description: "坚持民乐说唱融合路线，以舞台与作品完成跨圈层与跨文化传播。",
    conditions: {
      minTurn: 144,
      requiredFlags: ["performedZhukelingNewRap", "albumRouteFusion"],
      minStats: {
        creativity: 270,
        stage: 250,
        popularity: 230,
        authority: 160,
        reputation: 210,
      },
    },
  },
  {
    id: "ending_branch_gold_producer",
    category: "branch",
    title: "幕后造梦者 · 金牌制作人",
    description: "以持续创作为核心，完成大量作品打磨并建立稳定的制作人影响力。",
    conditions: {
      minTurn: 144,
      minStats: {
        creativity: 280,
        authority: 170,
        reputation: 180,
        tacit: 105,
      },
      requiredCounters: {
        songwritingSessions: 24,
      },
    },
  },
  {
    id: "ending_branch_stable_star",
    category: "branch",
    title: "稳步长红 · 并肩远航",
    description:
      "你们没有一夜封神，却把每个回合都走得扎实。作品与舞台稳步累积，口碑和人气在时间里沉淀。只要并肩不散场，这条路就会一直向前。",
    conditions: {
      minTurn: 144,
    },
  },
  {
    id: "ending_hidden_echo",
    category: "hidden",
    title: "双向奔赴 · 宇宙回响",
    description: "她与企划、家人、队友和小喇叭们彼此照亮，在《宇宙里的星轨》与鸟巢灯海中完成真正的双向奔赴。",
    conditions: {
      minTurn: 144,
      minStats: {
        tacit: 155,
        creativity: 345,
        stage: 375,
        popularity: 385,
        resilience: 165,
        bond: 290,
        authority: 185,
        reputation: 265,
      },
      requiredCounters: {
        fanInteractions: 72,
      },
    },
  },
  {
    id: "ending_failure_f1_unstarted_seventeen",
    category: "failure",
    title: "遗憾结局 · 未启程的十七岁",
    description:
      "你把说唱留在「爱好」一栏里，她也把耳机里的节拍越调越小。大学几年照常上课、照常毕业，只是那个在海报前亮了一下眼睛的女孩，再也没有把歌词本递到你面前。你们还是朋友，但她心里的「17」没和你一起出过门——企划并肩的故事，在起点就悄悄合上了。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
  {
    id: "ending_failure_f2_mic_blank",
    category: "failure",
    title: "遗憾结局 · 话筒前的空白",
    description:
      "队训那晚她替你圆了场，自己却再也没站回圆心。社团群里偶尔还有人 @她，她笑笑说忙。联结淡了，韧度也磨薄了，你们之间剩下的是礼貌的问候，不再是「下一句押什么」。她没说你错了，只是音乐不再是你们共同的动词——这条企划线，停在了空话筒前。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
  {
    id: "ending_failure_f3_draft_never_sent",
    category: "failure",
    title: "遗憾结局 · 停在草稿箱里的光",
    description:
      "「再打磨打磨」成了年复一年的咒语，工程文件停在「最终版」第 17 稿。没有全平台发布，就没有被陌生人听见的回声；没有回声，毕业季那些大舞台与节目的叙事便接不上榫。时间替你做了决定：有些光，不发出去，就永远只是屏幕里一截没温度的波形。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
  {
    id: "ending_failure_f4_slowly_unheard",
    category: "failure",
    title: "遗憾结局 · 慢慢从未被听见",
    description:
      "《慢慢》只在社团活动室绕梁，没有流进更大的海里。人气与创作都没抬到能被节目组「循环作品」的高度——那个上海打来的陌生号码，在平行时空里响过，在你这条时间线上却始终没有接通。她收起 offer 与邮件之间撕扯的那只手，不是因为选了稳定，而是因为从来没人递来那张「必须选」的入场券。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
  {
    id: "ending_failure_f5_stage_eliminated",
    category: "failure",
    title: "遗憾结局 · 灯没为她亮",
    description:
      "初舞台你替她选了更炸的快嘴，现场很燃，却把「王澳楠是谁」留在了幕后。分数与镜头一路吃紧，到决赛夜前，创作、舞台与联结都没撑到能走进那条全国直播的叙事门槛——赛程在半路拐弯，PlaneA 的灯牌没等到她。上海的风很大，你们拖着行李箱回程时，耳机里切回的那首 demo，比台上更像她本人。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
  {
    id: "ending_failure_f6_trust_break",
    category: "failure",
    title: "遗憾结局 · 最佳企划，到此为止",
    description:
      "企划默契跌到冰点——不是某一次选择的对错，而是无数次「你定吧」背后，她再也看不见自己的声音。新章节翻开那天，她没有吵架，只是把共享日程从你手机里撤下，说想自己试一试。你仍是故人，但不再是她人生里那个「敢把后背交给谁」的名字。并肩十年之约，在这一页提前落款。",
    conditions: { requiredFlags: ["__fatal_never__"] },
  },
];

/**
 * 背景 10 张 + 立绘 6 张，均为 PNG；文件名与资源 ID 一致（如 `bg_campus.png`）。
 * 音频：`public/topstar/audio/` 下 OGG（与 `assets` 中扩展名一致）；可改为 MP3/WAV 并同步改 URL。
 * 路径相对 `evemusic/public/`，见 `顶流企划/美术资源路径与替换说明.md`。
 */
export const assets: AssetManifest = {
  backgrounds: {
    bg_campus: "/topstar/backgrounds/bg_campus.png",
    bg_club_room: "/topstar/backgrounds/bg_club_room.png",
    bg_dorm_night: "/topstar/backgrounds/bg_dorm_night.png",
    bg_recording_studio: "/topstar/backgrounds/bg_recording_studio.png",
    bg_variety_stage: "/topstar/backgrounds/bg_variety_stage.png",
    bg_studio: "/topstar/backgrounds/bg_studio.png",
    bg_concert: "/topstar/backgrounds/bg_concert.png",
    bg_gala: "/topstar/backgrounds/bg_gala.png",
    bg_birdnest: "/topstar/backgrounds/bg_birdnest.png",
    bg_hotel: "/topstar/backgrounds/bg_hotel.png",
  },
  portraits: {
    eve_campus: "/topstar/portraits/eve_campus.png",
    eve_career: "/topstar/portraits/eve_career.png",
    eve_breakout: "/topstar/portraits/eve_breakout.png",
    eve_topstar: "/topstar/portraits/eve_topstar.png",
    eve_stage_mic: "/topstar/portraits/eve_stage_mic.png",
    eve_flute: "/topstar/portraits/eve_flute.png",
  },
  bgm: {
    chapter1: "/topstar/audio/bgm_chapter1.ogg",
    chapter2: "/topstar/audio/bgm_chapter2.ogg",
    chapter3: "/topstar/audio/bgm_chapter3.ogg",
    chapter4: "/topstar/audio/bgm_chapter4.ogg",
  },
  sfx: {
    click: "/topstar/audio/sfx_click.ogg",
    unlock: "/topstar/audio/sfx_unlock.ogg",
  },
};

export const topstarData: TopstarGameData = {
  chapters,
  chapterMaps,
  storyEvents,
  fillerStories,
  routineEvents,
  shopItems,
  recurringEvents,
  endings,
  assets,
};

export const turnIndex: TurnIndexEntry[] = Array.from({ length: 144 }, (_, index) => {
  const turn = index + 1;
  return {
    turn,
    id: `turn_${String(turn).padStart(3, "0")}`,
    chapterId:
      chapters.find((item) => turn >= item.turnRange[0] && turn <= item.turnRange[1])?.id ??
      "chapter1",
    dateLabel: getTurnDateLabel(turn),
    keyEventId: storyEvents.find((event) => event.turn === turn)?.id,
    recurringEventIds: recurringEvents
      .filter((event) => event.turns.includes(turn))
      .map((event) => event.id),
  };
});
